### ISSUE TITLE
FE8 Strict weapon + randomized enemies bug

### ISSUE THREAD

**Issue by Danice123** [lushen124/Universal-FE-Randomizer#118]
Specific issues:

Dark mages end up with only a staff they cannot use early game. 

First fog mission had an Archer without a bow

Ines+garik mission had knight without a weapon at all

**Comment by lushen124** [comment]
Can you provide your seed and your settings? (Changelog works too).

**Comment by Danice123** [comment]
[changelog.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/3101859/changelog.zip)
