### ISSUE TITLE
Application Closes On Its Own

### ISSUE THREAD

**Issue by 231joe33** [lushen124/Universal-FE-Randomizer#12]
Hello. I am having trouble using the application which is strange because it was working fine last night. The app opens up but when I try to load the ROM (A Clean FE8) the entire app closes on its own. I tried reinstalling the app, and then I even restarted my computer but the same thing happens. I also tried using the JAR file but the same thing also happens. I'm on Windows 7.

**Comment by lushen124** [comment]
Hey, sorry. I was trying to add a feature so that the randomizer would remember your previous settings, but I introduced a bug for the GBA settings. I'll put up a hotfix later tonight when I get off of work.

**Comment by 231joe33** [comment]
Oh, perfect. Thanks! I was surprised to see this was updated I love all the new changes. I was still using the old randomizer and was wondering if anything new had happened. Thanks for the update.

**Comment by lushen124** [comment]
Ok, 0.7.5 is out now. Let me know if you still run into issues. It will wipe any previous randomization settings you might have set, just in case the old data isn't restore-able, but you should be able to load games again.

**Comment by lushen124** [comment]
👍
