### ISSUE TITLE
FE4: Error while randomizing classes

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#134]
No idea what's happening
![Schermata 2019-04-22 alle 17 33 24](https://user-images.githubusercontent.com/40038845/56508591-00047c00-6525-11e9-81af-7f84feb0a8c5.png)

**Comment by lushen124** [comment]
Sounds like you got a class with no usable items somehow. Can you paste me that seed you're using?

**Comment by koumal8** [comment]
I don't have the changelog because it wasn't generated, but the seed is there: Sauöööölooo; maybe it's due to the "ö"s?

**Comment by lushen124** [comment]
Nah, if you got that far, then it came up with a seed just fine. I just wanted to see if I can reproduce it on my end. Based on the stack trace, it looks like you managed to get a class that had no usable weapons, specifically on a child character, probably due to blood or some other restriction.
