### ISSUE TITLE
FE7: Failure to randomize

### ISSUE THREAD

**Issue by Kachurin** [lushen124/Universal-FE-Randomizer#135]
![yunebug](https://user-images.githubusercontent.com/44204869/56528691-97fe6780-651d-11e9-9add-7e9edb43cf7e.PNG)
Very unsure as to what's going on. This is happening consistently, I've tried to get multiple clean FE7 roms from different sources to no avail. First time trying to use this randomizer so the fix might be simple, would appreciate some help.

**Comment by lushen124** [comment]
Ah, I found the issue. See, I recently added the ability to include or exclude lords from randomization, and specifically for FE7, the randomizer also modifies the character select screen to match the new lords when randomizing recruitment. Unfortunately, it assumes lords are randomized, so if it's not, when it goes to look for the replacement lords, it can't find them.

Temporary work around is to check "Include Lords" under the recruitment options. I'll put a fix in.

**Comment by Kachurin** [comment]
ahh I see. That works, Thanks!
