### ISSUE TITLE
FE7: Pallette not transitioning 'nicely'.

### ISSUE THREAD

**Issue by Zswords** [lushen124/Universal-FE-Randomizer#137]
Not a huge deal, pallettes, but I didn't know where else to just have 'here's a few instances of pallettes not cleaning up' that you might, either want or not.

Guy Knight Lord:  
![SSLP Save_09](https://user-images.githubusercontent.com/8367391/56558760-956b3480-6554-11e9-8981-bb227f698895.png)

and Khent Female Bishop: 
(Less bad, but it spontaniously made his outline bright red when it wasn't as a cleric): 
![SSLP Save_08](https://user-images.githubusercontent.com/8367391/56558814-c0558880-6554-11e9-894b-a37e2da6419e.png)
Cleric: ![SSLP Save_03](https://user-images.githubusercontent.com/8367391/56558938-0f9bb900-6555-11e9-8be7-8bb7190cb6c9.png)

This is the same save and seed from the growths discussion we had earlier: https://gyazo.com/75e78e4ba70c89f399c88f8ec3883e05

**Comment by Kachurin** [comment]
![image](https://user-images.githubusercontent.com/44204869/56598290-3fcd7100-65c2-11e9-8628-d0d88bca6645.png)
This also happens with soldier Sain.

**Comment by lushen124** [comment]
Yeah, I think when I re-did the palette info, I might have messed up some of the color indices for some classes. Can you let me know which classes/characters seem to exhibit this issue? The logic generally goes by class -> class, and I think I might have used FE6 indices for FE7.

**Comment by Zswords** [comment]
So in this case it was:
Myrmidon (Guy) and Swordmaster (Guy) > Eliwood Lord and Knight Lord.
Paladin > Female Bishop

and while I don't think that Sain pallette is bad at all, just a little unique:
Cavalier > Soldier.

**Comment by Lewa263** [comment]
With randomized recruitment but no class changing, I had Myrmidon Guy show up in place of one of the cavaliers, and his color scheme was messed up even in his default class. I think that was with 0.8.3, and I regrettably didn't take a screenshot.

**Comment by lushen124** [comment]
It looks like I definitely broke some of the color indices for FE7. I may just end up redoing the color indices for FE7. I recently re-did the palette logic to better support FE8 (since its palette system is a bit more advanced than FE6 and FE7).
