### ISSUE TITLE
FE4: Class appearing incorrectly on spawn

### ISSUE THREAD

**Issue by LJCLilio** [lushen124/Universal-FE-Randomizer#138]
This has happened a couple of times, only in generation 2 though. Characters will appear to be in a different class than they actually are when they appear on the map, and will only become "normal" again when the next chapter starts. It seems to happen only to units who don't start off blue.

https://imgur.com/a/5kcdsgV

https://imgur.com/a/6BcsDEt

Ced is functionally a Master Knight in all ways except map sprite.

**Comment by LJCLilio** [comment]
I should mention as well, this doesn't seem to happen every time, nor to every unit. It happened once to Tine, but then not again, it's not happened to Altena or the axe boys at all

**Comment by lushen124** [comment]
I think this is a bug in vanilla, actually. Have you been using the build in save/load function, or are you relying on save states? FE4 has a few quirks when you don't turn off the game for a long time.

**Comment by LJCLilio** [comment]
I've been relying on savestates. I had no idea that's something that could just happen in vanilla, that's super weird.

**Comment by lushen124** [comment]
Yeah, lots of weird stuff can happen. Things like Seliph having an extra leadership star, and I think in vanilla, I think it was the three mage sisters that had the same issue where the map sprite didn't agree with their actual class.
