### ISSUE TITLE
FE7: Softlock with randomized recruitment at Rath's scripted kill in chapter 6

### ISSUE THREAD

**Issue by Kachurin** [lushen124/Universal-FE-Randomizer#139]
![image](https://user-images.githubusercontent.com/44204869/56598165-fa10a880-65c1-11e9-908a-01b374b0559f.png)
I read that you had logic to ensure Rath was a ranged class so this couldn't happen, but I suppose there's no logic to stop it from happening with randomized recruitment? You probably know about this, but I figured I'd put it out there anyway.

**Comment by lushen124** [comment]
There should be logic to stop it for randomized recruitment, but it doesn't seem to be taking? Let me take a look at that example. Do you have the seed you used?

**Comment by Kachurin** [comment]
Unfortunately I do not, apologies.

**Comment by Zswords** [comment]
I wonder if Dart has a Hand Axe in his inventory that he didn't start equipped with, and the logic said 'Hand Axe, good enough!'?

**Comment by Kachurin** [comment]
I don't imagine that's the case, since it tries to match the inventory to what rath would normally have but in the new weapon type. In this case he should have the emblem axe and a vulnerary afaik

**Comment by lushen124** [comment]
Now that you mention it, did you use strict matching for weapon assignment? There's a good chance that might have overridden the fact that he was supposed to receive a hand axe, but couldn't match to it because it's a "basic" weapon Rath normally has.

**Comment by Kachurin** [comment]
I did indeed use strict matching. That's probably it
