### ISSUE TITLE
Bonewalker with Incorrect Weapon

### ISSUE THREAD

**Issue by 231joe33** [lushen124/Universal-FE-Randomizer#14]
https://imgur.com/a/51dms5h

I have seen this happen twice now but I do not think it is intended.

**Comment by lushen124** [comment]
Definitely not intended. What settings did you use? Do you have the changelog?

**Comment by 231joe33** [comment]
https://imgur.com/a/S6NsXlf

**Comment by 231joe33** [comment]
https://imgur.com/a/ZaviglQ

I just wanted to add that it the archer bonewalkers are not holding the right weapons as well.

**Comment by 231joe33** [comment]
Prologue and Chapter 1.

I know in the prologue all the enemies are ax-wielders so that probably explains the issue with the bonewalker (sword) with an ax.

I just checked in Chapter 1 the gargoyle was originally an ax-wielder as well and the bonewalker(archer) was a lance soldier. So it looks like only the class is changing and the weapon stays the same, but only if the class change is into a monster.

**Comment by lushen124** [comment]
Oh... lol I found the issue. I refactored the GBA stuff recently, so I missed a minor detail. Namely, for monster classes, I assume they only have one weapon, so I return the same item as the one passed in for the replacement. But this is only true for monster classes that use monster weapons. Gargoyles and Bonewalkers don't do this.

**Comment by 231joe33** [comment]
Oh so the weapon never changed when changing to Bonewalkers or Gargoyles because they don't have 
a monster weapon?

**Comment by lushen124** [comment]
The logic was that all monster use a different set of logic to determine what an appropriate sidegrade is, since Rotten Claws don't exactly have a rank attached to them. The logic was assuming that all monsters use monster weapons, but the mapping doesn't have anything for the ones that use human weapons.

**Comment by 231joe33** [comment]
Oh, I see.

**Comment by lushen124** [comment]
I went ahead and updated version 0.7.5 for Windows. Give that a shot.

**Comment by 231joe33** [comment]
It's fixed now. Thanks for the update. I'll let you know if I find anything else.

**Comment by lushen124** [comment]
👍
