### ISSUE TITLE
Growth Min/Max

### ISSUE THREAD

**Issue by primomaterial** [lushen124/Universal-FE-Randomizer#140]
It would be amazing if you could add min or max options to the growth randomization much like the Con randomization. 

In essence to create random growths but in standard FE distribution. 

In current system a lot of growths end up being totally unusable (0-20%)

**Comment by Zswords** [comment]
I was also going to suggest this as a potential setting for the Delta/Same Total settings, just to help make things a little less polarizing. 120 Strength is great and all, but the 25 HP, 15 SKill and Speed that it can come with effectively makes them a non character.

I'd also, like, but depends on how everything is set up, like to see if you can have the 'Biase HP' setting factor in AFTER that limit roll. The settings I have in mind is like '15-60 growth cap, with 25 Base Growth Total Variance', but then having that HP limit be 35-80 so I don't have to deal with Fates HP Syndrome.
