### ISSUE TITLE
Mostly GBAFE specific feature requests (and one bug)

### ISSUE THREAD

**Issue by SirBlackMage** [lushen124/Universal-FE-Randomizer#141]
Hey, I've been using your randomizers (both the old universal one and Yune) for quite a while. I've really been enjoying my time with it and Yune is already really good in its current state, but I do have some feature requests and one bug to report. Everything here is pretty much GBA-specific since those are the games I mainly play (mostly FE7). I included explanations as to why I feel these features would be nice to have. Sorry if you'd prefer each request having its own issue (for adding milestones), but I figured this would be much preferred to me spamming 9 consecutive posts.

FEATURE REQUESTS:

These options would, of course, all be toggleable.

Extend 'Safe Basic Weapons' to steel weapons (and tome equivalents), as well as javelins and hand axes. I like the idea of random weapon effects, but I feel like steel and basic throwing weapons are too common to receive any effects.

Remove certain classes from the randomization pool for player and/or enemy units. I mostly write this because I'm not a fan of generic enemy lords. They're really weird to me.

When using cross-gender randomization, still use the correctly gendered class when possible. For example, when a male unit would be randomized into a female Mage, instead use the male Mage class. This is mostly to allow the flexibility of both genders having access to all classes, while still using the correct gender for a character whenever possible.

Apply the FE7 Gameplay Reversion Hack before randomization. It's a patch that mostly restores the gameplay to the Japanse original. Includes changes such as: 3x effectiveness, slightly differing terrain bonuses, higher boss stats, different enemy inventories, and a more difficult final chapter. The big one here is 3x effectiveness, as it actually makes archers and effective weapons decently useful like in the other GBA games.
Link to the hack: https://serenesforest.net/forums/index.php?/topic/83914-fire-emblem-7-gameplay-reversion-hack/

Allow all classes to use Prf weapons. To take FE7 as an example, set Mani Katti, Rapier and Wolf Beil to C or B rank, set all legendary weapons to S rank. I'm requesting this because most of the time, personal weapons are just lying around collecting dust (if you randomize lords).

Randomize droppable enemy items. Would mostly be interesting when also upgrading enemy inventories. Not a very important thing, just thought I'd mention it.

Randomized Shops. Pretty self-explanatory, although it would require some logic to remove the possibility of certain characters running out of usable weapons completely. Also maybe randomize item prices?

Implement Some way to get more promotion items. Not sure what that would be, but I just wanted to mention that I'm usually strapped for promo items when playing FE7 with randomized rewards. The secret shop that sells them also comes way too late to be useful. These factors sometimes force me to play with only a few overleveled characters.

BUG REPORT:

I was playing FE7 and buffed enemy growths by 100% via Scaling Buff, which made most enemies' HP really low for their level (it appeared to be their class base). I'm talking about things like the level 10 Snipers next to Kishuna having 21 HP. The only enemies that weren't affected by this seemed to have a class HP growth of ≤ 100% (after doubling growths), which I suspect would be the cause.

Also not really a bug, but it'd be great if 'Include Special Classes' specified what classes are considered 'special'.

Thanks for reading this far, sorry for the essay.

**Comment by Zswords** [comment]
Some of these are definitely similar to what I've experienced or was thinking, especially the promotion item situation. I randomized thieves because I wanted Matt and Legault to have time to shine, and I've been editing all promotion item stealables to be droppables instead when they've come up because the game didn't give me a thief. (Well, Wallace is a thief. RiP) Having either some, more in depth logic that forces a thief before Pirate Ship, or having the randomizer adding the droppable tag/more dropped promotion items would be cool.

IMO it less makes the game 'easier' and more 'makes more options viable', which is always a plus.

**Comment by SirBlackMage** [comment]
Yeah, that's pretty similar to my experiences. I did get an early Thief in my last playthrough but was playing with greatly increased enemy and boss stats, so he literally couldn't steal anything anyway. I resorted to making the items droppable too, as well as adding a few chests with promo items across the game.

I definitely agree with your point on viability. Only being able to promote a few characters doesn't really make the game too much harder, since FE7 is heavily focused on enemy phase. As long as you have two or more strong characters with 1-2 range, you're pretty much fine combat wise. The only maps where having few good characters is really problematic on are ones that enforce swift play like Battle Before Dawn. So while having a large roster generally isn't necessary, it makes for a much more varied and interesting experience. More options are always good, especially for a randomizer. 

And now that I've mentioned Battle Before Dawn, I might as well briefly go over something I forgot to mention earlier. With increased enemy growths, Zephiel is liable to die before you can realistically make it to him. If you don't have a rescue staff, lots of mounts or some very good luck with the RNG, protecting him could prove to be impossible. I haven't had this happen yet, but I've had some very close calls, so I figured I'd mention it. Maybe his growths could be buffed as well to match the enemies'?

**Comment by lushen124** [comment]
I'll address the bug for 0.8.5, but I'll leave the other enhancements for post 0.9.0 since I wanted to get started on some FE9 stuff soon.

**Comment by SirBlackMage** [comment]
Great, sounds good to me, I am pretty excited about that FE9 support! I'd love to give a donation for all the work you've done here, but I don't think you accept any, do you?

**Comment by lushen124** [comment]
TIL the autoleveling routine for enemies only respects 7 bits. At 127% HP growth, I got a level 20 myrm to 38 HP. At 128% HP growth, he dropped back to 16 HP. This applies for all other stats too, it's just that in your example, none of the other stats come close to that much.

**Comment by lushen124** [comment]
I don't take donations because that tends to lead to expectations. 🙃 

Maybe once v1.0 ships, I might consider it.

**Comment by SirBlackMage** [comment]
Ah, so it was 128% and not 100%. Didn't check hard enough to specify the percentage that breaks it, but good to see that you figured it out. And nice to know about the donation thing, I'll get some money ready to throw at you, should you start accepting them. 👍
