### ISSUE TITLE
FE7: Living Legends Bandit Pair Weapon Ranks

### ISSUE THREAD

**Issue by Zswords** [lushen124/Universal-FE-Randomizer#142]
https://youtu.be/xPrFr3npS5E?list=PLkNMvp7xeFX08efMeEvzYaurUvcrhwkvI&t=5682

Kinda covers it at that moment, but Paul and Jasmine spawned with an E in all their weapon ranks. Jasmine is a druid and Flux is a D, so can't fight me. Just, run around healing people with the two heal sticks that all Druid/Sage/Bishops seem to spawn with. (Yet an enemy replacing someone who ONLY had a staff spawns with nothing.)

Still this seed btw: https://gyazo.com/75e78e4ba70c89f399c88f8ec3883e05

**Comment by lushen124** [comment]
Weird. Pretty sure I had logic to make them adopt the higher of their two ranks. Paul and Jasmine are normally warriors with C axes and E bows, so it sounds like it took the E over the C, oddly enough.

As for the starting weapons, I suspect the strict matching is still causing issues, at least with classes that can use staves. I thought I only applied that to playable characters, but maybe it's also applied to enemies too. I'll take a look.

**Comment by lushen124** [comment]
Oh... I guess IntSys got lazy. Unlike most other characters, Paul and Jasmine have no weapon ranks defined on their character normally, using their class defaults instead. The randomizer doesn't quite handle this case properly, giving them E ranks in their class defaults. I should just use their class ranks as is.

Still looking into the staff issue on other minions.
