### ISSUE TITLE
CON Randomized When Not Selected

### ISSUE THREAD

**Issue by 231joe33** [lushen124/Universal-FE-Randomizer#15]
https://imgur.com/a/z22jUiq

I have CON Randomized off but

https://imgur.com/a/NRzIag2

I feel like their CON is changing anyway because of the class they are changing into?

**Comment by lushen124** [comment]
Yeah, when I randomize classes, I don't adjust their CON. Their final CON will change depending on the class they randomize into. Lords actually have most of their personal bases at 0, so the class determines almost everything (except LCK). Eirika's personal CON is 0, so she'll get whatever CON the class she randomizes into gets.

For another example, Kyle has 10 CON vs a normal Cavalier's 9, so his personal CON is 1. If he were to randomize into Ephraim Lord, he would get his 1 CON + Ephraim Lord's 8 CON for a total of 9 CON.

**Comment by 231joe33** [comment]
Oh.

OH right it doesn't randomize the base stats of their CON only if you select it but it still changes anyway because of the class.

Sorry about the confusion.

**Comment by lushen124** [comment]
No worries. 🙂
