### ISSUE TITLE
Strict Weapon Rank Weapon still not working

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#151]
https://www.dropbox.com/s/puc7v17957c1jb4/Fe6Random.html?dl=0

Marcus was replaced by Noah with 2 iron swords on Hard Mode

**Comment by lushen124** [comment]
I think #152 fixes some of this, but in your case, randomized recruitment is involved, which is a nice reminder that I need to also apply the same logic when doing randomized recruitment.

TIL, not all characters have their weapon ranks defined on their character data. A lot of them actually leverage the class defaults, which I wasn't accounting for.
