### ISSUE TITLE
GBAFE: "Improve Enemy Weapons" gives all enemies bonus crit

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#154]
With the "Improve Enemy Weapons" option turned on, all enemies have S ranks on all their class-appropriate weapons. That means they get a constant 5 crit bonus. It's not that big of a deal, but I thought I'd say something in case you hadn't noticed.

**Comment by koumal8** [comment]
I never noticed it but question: why are they even getting S rank in all their weapon ranks? I thought the AI autoleveled their weapon ranks based on the weapons they were given.

**Comment by lushen124** [comment]
I gave them all S rank when you improve enemy weapons so that they have the possibility of getting one of the end game weapons, but I forgot that S rank gives bonuses. I might just cap it at A instead of S when improving enemy weapons.

**Comment by SirBlackMage** [comment]
I  was wondering why this was, I had no clue regular enemies could get S-Rank weapons, only had this happen to me with bosses so far. That idea does sound pretty cool, too bad about the Hit/Crit bonus getting in the way.
