### ISSUE TITLE
FE7: Enemies with inappropriate sword weapon levels

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#155]
I have all enemies in randomized classes, and I keep finding enemies with sword weapon levels in non-sword classes. They never have swords in their inventory, thankfully, but something is clearly going wrong. I haven't seen this for any other weapon type, only swords, and it's always rank C. I'll attach some screenshots I got in Chapter 8 LHM, plus the settings I used for this one from the log.

![sword_pirate](https://user-images.githubusercontent.com/18605346/57115561-5176ed00-6d15-11e9-9e24-f7eac71b4335.PNG)
![sword_wyvern](https://user-images.githubusercontent.com/18605346/57115562-5340b080-6d15-11e9-9e10-1b3e7449b802.PNG)
![yune_settings_2](https://user-images.githubusercontent.com/18605346/57115593-6eabbb80-6d15-11e9-86af-c2b405d12a6e.PNG)

**Comment by lushen124** [comment]
This is actually resolved in #152. Turns out, some minion characters have overriding weapon ranks, which the old version didn't account for. I pulled those in with that fix so that the ranks should be consistent.
