### ISSUE TITLE
Fully randomized adjusted HP growth calculated incorrectly

### ISSUE THREAD

**Issue by newThrowaway** [lushen124/Universal-FE-Randomizer#16]
Hi, I've just found your new randomizer. Haven't tried it yet, but found some problem with the fully randomized growths:

### What should happen

HP growth is randomized in an equally distributed range from (minGrowth + (maxGrowth - minGrowth)/2) to maxGrowth.

### What happens

If HP growth is below threshhold, the threshhold is added **including the minGrowth**.
Thereby the minGrowth is added twice.

**Example:**
minGrowth = 30
maxGrowth = 90
threshhold = 60

In 50% of cases, the threshhold is added to the new growth.
Since new growth is always >= minGrowth, this means that there is a 50% chance to achieve maxGrowth.

### Possible solution

Only add the range, but not the minGrowth.
I would prefer to have separate inputs for min/max HP growth, but that is, of course, more time consuming to implement.

**Comment by lushen124** [comment]
Ah, I see what you mean. Nice catch!

The intent is to just make sure HP is in the upper half of the range specified, so what it really needs to do is make sure that any value below half is brought up to above half. And you're right, I just needed to add range/2 and not the entire threshold.

That said, I could make a second spinner set for HP. It would give the user more control, and it's not _that_ hard to implement.

**Comment by lushen124** [comment]
This should be resolved in 0.8.0.
