### ISSUE TITLE
Lyn's stats in-game don't match the log

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#160]
I'm using the new release 0.8.5, and I've found discrepancies between Lyn's stats in the game and in the log. I'll attach pictures. I randomized a few more times with the same settings and different seeds, and it kept happening. I haven't played through a full game to check, but the units in Eliwood and Hector's intro chapters do not have this problem. Only Lyn so far.
![wrong_lyn](https://user-images.githubusercontent.com/18605346/57339791-970e2e00-70f8-11e9-86d1-c0f3f451cc50.PNG)
![yune_settings_3](https://user-images.githubusercontent.com/18605346/57339793-99708800-70f8-11e9-8250-edf2d9a0d350.PNG)

**Comment by Zswords** [comment]
The Log uses the bases that would be given to Lyn in Hector/Eliwood mode if you never played Lynmode, and this extends to any character in Lyn Mode that later re appears in Hectiwood.
