### ISSUE TITLE
FE8: Starting rapier replaced when it shouldn't be

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#163]
I randomized recruitment for FE8 with lords included, slot classes, no randomized rewards, and weapons set to strict matching, but the Eirika replacement starts with an iron sword and is given a second sword as a reward. That second reward sword should be the rapier (and the iron sword shouldn't exist), but the second sword has never yet been a rapier for me. I've seen a slim sword and an iron sword so far.

**Comment by koumal8** [comment]
Assuming strict matching is working, the Rapier's Prf flag is set to the Eirika Lord Class which means that even if Eirika is randomized into a Sword using class, unless she's an Eirika Lord as in vanilla, she still can't equip the Rapier and as such the randomizer doesn't give her one. It's the same with Reginleif and (I think) Sigmund and Sieglinde, they're not tied to the characters of Eirika and Ephraim but to their Lord classes instead.

**Comment by Lewa263** [comment]
Oh, thanks for pointing out that I forgot a relevant setting. Classes are not randomized. Eirika's replacement has Eirika's default class.

**Comment by koumal8** [comment]
Oh, then you'll have to wait for Lushen on this yeah

**Comment by lushen124** [comment]
Weird. If you disabled randomized rewards, then that Rapier should never be changing, though I forget if I made the Rapier a special case. The reason why she starts with an Iron Sword is blanket logic that makes sure all characters start with weapons. I'll take a look.

**Comment by lushen124** [comment]
I'm leaving in the logic to make sure attacking classes always have weapons because that logic is necessary to give formerly pacifist characters (like former dancers) a weapon to start with instead of having nothing. There's probably better ways to get it done, but I'm leaving this logic in for now and we can revisit later.
