### ISSUE TITLE
FE8: Crash when trying to include Creature Campaign units in randomized recruitment

### ISSUE THREAD

**Issue by Lewa263** [lushen124/Universal-FE-Randomizer#164]
Every time I check off the Include Creature Campaign NPCs setting on randomized recruitment, the randomization fails, with an error message like this:
![error](https://user-images.githubusercontent.com/18605346/57576109-570fb980-741e-11e9-8f48-24d890896760.PNG)
I never tried that option before 0.8.5, so I don't know whether it only broke in the most recent release.

**Comment by lushen124** [comment]
Duplicate with #175
