### ISSUE TITLE
FE7: Matthew has lost his affinity.

### ISSUE THREAD

**Issue by Kachurin** [lushen124/Universal-FE-Randomizer#167]
![image](https://user-images.githubusercontent.com/44204869/57738880-4dd15780-767f-11e9-8b07-9704dbe0c195.png)
![image](https://user-images.githubusercontent.com/44204869/57738884-52960b80-767f-11e9-8d9f-4ef1fb7d52c4.png)
![image](https://user-images.githubusercontent.com/44204869/57738891-56299280-767f-11e9-8dd5-7eef0de3542a.png)
Images show the lack of affinity, what happens when he gets a support in this state, and the settings I used.
For some reason Matthew just... doesn't have an affinity. Quite game-breaking after he unlocked his first support, funnily enough. I've got no idea what caused this, never seen it before.

**Comment by jugglerpanda** [comment]
The same issue also happened to me in FE6. My Roy randomized into Chad with no affinity, and the associated support bonuses basically make Chad! Roy and all of his support partners godlike.
