### ISSUE TITLE
Cath spawn in FE6 Chapter 6 soft locks the game

### ISSUE THREAD

**Issue by afsanta** [lushen124/Universal-FE-Randomizer#17]
I was recently playing a randomized version of FE 6 that I created using Yune on Ubuntu 16.04, and when I got to chapter 6, the game soft locked on the enemy phase after Cath spawned on turn 5.

**Comment by lushen124** [comment]
Thanks! I received reports of this from other people as well. I'll take a look at it. 👍

**Comment by lushen124** [comment]
0.8.0 should move Cath one space to the left in Chapter 6 now, so she should be right next to the wall instead of spawning in the wall. Let me know if you run into issues again and I'll look into it some more.
