### ISSUE TITLE
Max/Min Crit randomization

### ISSUE THREAD

**Issue by Rmccallu** [lushen124/Universal-FE-Randomizer#170]
Why isn't there a category for altering the crit of a weapon? I didn't find it to be too big of a deal, but then in one of my randomized games the reinforcements every turn on the last fog of war map in SS were 2 mage knights with 50 crit tomes. Additionally, a recent game gave me 55 crit Slim Lances, and that became a boring, easy run way too fast. Is there any way we could set a limit to how much the bonus "enhance crit" gives?

**Comment by lushen124** [comment]
Seems like a reasonable addition. The current logic picks a random crit amount between 20 and 50 (in increments of 5). The UI would look a bit weird to fit that in, but it should be possible to allow custom crit ranges.
