### ISSUE TITLE
Editing weapon property weights

### ISSUE THREAD

**Issue by Rmccallu** [lushen124/Universal-FE-Randomizer#172]
Could there be a way to edit the chances of a random modifier being added to a weapon? I like having Devil and Eclipse in the mix, and some of my favorite moments have been from enemies having these weapons, but it sucks when they're on so many of my weapons. Plus, I've wanted to make the better modifiers (brave, killer) less common and boost up the rate of +5 stat, as right now it seems to choose stat boost at the same rarity as other bonuses, then choose a random bonus after that, and I'd rather have every stat boost be just as likely as any other property, especially since they're good bonuses but don't risk trivializing the game.

**Comment by lushen124** [comment]
Not a bad idea, I'd just need to figure out a way to concisely provide those controls within the confines of the UI. It does scroll, but I prefer to present it in a way that didn't scroll. Maybe I could break it out into a different window.
