### ISSUE TITLE
FE8 Error randomizing recruitment?

### ISSUE THREAD

**Issue by HyperMushrambo** [lushen124/Universal-FE-Randomizer#175]
Whenever I try to randomize I get an error randomizing the recruitment. I've toyed around with the settings but I don't know what I'm doing wrong. I tried using a different rom to see if that works but I'm getting the exact same error message. Here's the error message and the settings I selected. Anyone know what I'm doing wrong? 
![FE rando error2](https://user-images.githubusercontent.com/51077852/58409079-86ccdd00-802c-11e9-9e48-edbf10347451.PNG)
![FE rando error1](https://user-images.githubusercontent.com/51077852/58409080-86ccdd00-802c-11e9-8237-9c897090de96.PNG)

**Comment by lushen124** [comment]
Ah, I see the problem. When I added creature campaign NPCs, I didn't yet revamp the weapon ranks system. The problem is that the NPC version of the CC characters have different classes. Hayden, in particular is listed as a Peer, which isn't a class that the randomizer recognizes (since it's not one it normally uses), so it fails on that. I'll work on a fix for it, but in the meantime, you should be able to get around it by disabling **Include Creature Campaign NPC's** under Recruitment options.

**Comment by HyperMushrambo** [comment]
> 
> 
> Ah, I see the problem. When I added creature campaign NPCs, I didn't yet revamp the weapon ranks system. The problem is that the NPC version of the CC characters have different classes. Hayden, in particular is listed as a Peer, which isn't a class that the randomizer recognizes (since it's not one it normally uses), so it fails on that. I'll work on a fix for it, but in the meantime, you should be able to get around it by disabling **Include Creature Campaign NPC's** under Recruitment options.

Ahh dang that's such a shame! I really was hoping to play with them in there because I love all those characters and was hoping to have some of them join T_T Do you think it'll be a difficult/possible fix? If you think it'll be doable (or something you even want to work on any time soon which is totally understandable if not) I might just wait until it's fixed to play it (and play some Blazing Sword in the meantime lol).

**Comment by lushen124** [comment]
It shouldn't be hard to fix... Just a matter of not linking the NPC versions to the CC versions (unless that causes other issues), but I'm also currently busy with IRL stuff and I've cleared the way for FE9 support as the next release, so it'll be whenever 0.9.0 releases (tentatively marked for the end of the year, but even that is optimistic).

**Comment by HyperMushrambo** [comment]
Ah darn that real life interfering with the important stuff! :P Ah well it's a definite shame but completely understandable. Good luck with getting the FE9 support working! :D Thank you for the response too!
