### ISSUE TITLE
Stuck Applying Changes

### ISSUE THREAD

**Issue by Exceedcharge** [lushen124/Universal-FE-Randomizer#18]
Hey there, I discovered your randomizer recently and it's super cool! I've been enjoying watching folks play randomized games so I wanted to hop in. The thing is, regardless of the version of Yune I use I get caught up on Applying Changes to the Rom and then it just sits there for 20-30 minutes. I don't know if this is normal or not. I thought it might be my Rom that was the issue but I went to the old GBA randomizer and tested it with those and it worked fine. 

Is there something I'm missing or am I just not waiting long enough for it to apply. 

Edit : Oh I feel like a total idiot now. A friend just told me the mistake I was making right as I typed this out. Sorry for wasting your time. I'ma  total dumbass

**Comment by lushen124** [comment]
Yeah, It shouldn't be taking more than 20-30 seconds, much less a minute. Let me know if you run into any other issues though. 😄
