### ISSUE TITLE
Nightmare Editing AFTER Randomization?

### ISSUE THREAD

**Issue by Jumpants** [lushen124/Universal-FE-Randomizer#180]
Is there any way to tweak a randomized FE4 rom in Nightmare or similar software after it's been randomized? I've tried a few times and all the settings are jumbled up (i.e. Sigurd randomized to a High Priest but his class displays in Nightmare as a Lance Knight) and any changes made don't affect the rom at all.

**Comment by lushen124** [comment]
If I were to guess, you have a unheadered ROM. A randomized game can be altered using Nightmare, but the nightmare modules that I know of expect headered ROMs. If you add 0x200 bytes to the beginning of the ROM file, everything should line up again.
