### ISSUE TITLE
Ch.15 Nomad Trooper Karel suddenly has 0 Spd (--)

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#184]
My Roy replacement is Karel and he is a Nomad Trooper with all capped stats. I just entered Ch.15 and suddenly the stat screen shows him having -- Spd; every enemy doubles him (so I assume the game calculates it as 0 spd) and regardless of the weapon I give him he has 35 Avoid (30 from his Luck stat + ?), even though the Steel Bow should weigh him down and decrease his avoid. I don't even know if this is an issue caused by the randomizer, but the reverse recruitment patch doesn't have problems with a Karel lord with absurd stats. Should I give you my save?

**Comment by lushen124** [comment]
Closing in favor of #196 since it seems to be the same issue.
