### ISSUE TITLE
Question About Randomizing Movement

### ISSUE THREAD

**Issue by Gorade01** [lushen124/Universal-FE-Randomizer#186]
So, this is less of an issue with the software itself and more with how you explained it, because, well you didn't answer something. If I randomize movement so that Knights have 6 move and Generals have 5, what happens when I promote a Knight to a General? Does the Knight get the plus 1 move upon promotion, making them a General with 7 move, or do they get brought down to 5 move? I feel like this is important info, and, if the former is true, maybe worth considering the latter as an option.

**Comment by lushen124** [comment]
Randomized movement does leave open the possibility of a unit potentially losing movement on class change.  Therefore, a Knight with 6 move will lose 1 move if all Generals only have 5 move.
Maybe it's worth having an option to ensure that promoted classes always have more move than their unpromoted counterpart. Admittedly I don't use this option very much, precisely for the reason you gave. :)
