### ISSUE TITLE
Error in creating randomized FE4 and FE6 roms

### ISSUE THREAD

**Issue by infactanoose** [lushen124/Universal-FE-Randomizer#187]
FE4 and FE6's Apply English Patch option do not work. When trying to create the randomized ROM, the program gets stuck at "Applying English Patch" 
The randomizer still works without the English Patch option enabled.
Note: I am using a Windows 7 computer with a 64-bit operating system.

**Comment by lushen124** [comment]
I don't seem to be able to reproduce this on either FE4 or FE6 on the newest 0.9.0 build. I haven't changed anything, so I'm not sure it would be fixed, but can you try this again? Feel free to re-open if you can reproduce it.

**Comment by infactanoose** [comment]
![cap1](https://user-images.githubusercontent.com/56520684/76909469-4f5c4500-6879-11ea-943d-68bbb7e3e500.PNG)
![cap2](https://user-images.githubusercontent.com/56520684/76909472-4ff4db80-6879-11ea-80c9-0f8d10c93abf.PNG)
I've tried again multiple times, and it still gets stuck on "Applying English Patch." I'm not sure if you can fix this, because it seems like no one else is having this problem.

**Comment by lushen124** [comment]
You can give this a shot. I suspect it's throwing an exception that's silently getting lost. This one will fail with the stack trace if there is an issue.
[Yune.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/4346324/Yune.zip)

**Comment by infactanoose** [comment]
It still gets stuck like it normally does for me. And it still crashes after I try to randomize another rom.
I'm not sure why this seems to only happen to me.

**Comment by lushen124** [comment]
The new version still freezes? That's surprising. What should happen is an error dialog telling you why it failed. If it's still just silently freezing, then it didn't throw an exception and it's somehow stuck in an infinite loop.

Ok, let's try this. Here's a build that will print out the console log of the randomizer as it's running. When you launch this one, press CTRL + SHIFT + C to open up the console log. It should look something like this:

![image](https://user-images.githubusercontent.com/1689159/77234603-fb997680-6b6c-11ea-9648-48e681bed12a.png)

Then you can load your ROM and randomize it, and a bunch of stuff should start filling that window. It does slow it down, so I wouldn't recommend it normally, but at least we can see where in the UPS patching it's getting stuck.

[Yune.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/4363784/Yune.zip)

**Comment by infactanoose** [comment]
I think I found the loop. When applying the patch, it constantly writes more and more bytes, despite not making any progress at all during that time. As seen in the second image, it continues this process even after the creation of the modified ROM was cancelled. This is what probably causes the crash.
![yuneloop](https://user-images.githubusercontent.com/56520684/77237036-690bce00-6b92-11ea-88c3-9f0cab94856f.PNG)
![yuneloop2](https://user-images.githubusercontent.com/56520684/77237038-6a3cfb00-6b92-11ea-8db4-36e935d66258.PNG)

**Comment by lushen124** [comment]
It actually should be doing that. I don't show any progress as it does the patching. As long as the offsets are actually increasing,  that should be ok. If the offsets are not increasing, that's the issue. On my machine, this takes about 24 seconds if the console window is open and about 8 seconds normally.

**Comment by lushen124** [comment]
For reference, this is where FE6 should end up:

![image](https://user-images.githubusercontent.com/1689159/77237585-ca2da480-6b86-11ea-8296-c743c6e17a5b.png)
