### ISSUE TITLE
Disable Cross-gender option for classes

### ISSUE THREAD

**Issue by AgitoShining** [lushen124/Universal-FE-Randomizer#188]
Maybe just a personal issue but seeing Hector as a cleric and Isadora as a brigand threw me off. Its funny at first but I didn't like it going forward. I think its a good option to add into the randomizer.

**Comment by TWACC** [comment]
Agreed. Seeing Gilliam as a recruit or both Ephraim and Eirika as mages of the opposite sex can be funny but the novelty doesn't last. Most units including enemies got gender swapped in my most recent game. I would very much like the option to disable it.
