### ISSUE TITLE
Program won't open

### ISSUE THREAD

**Issue by Y-Guy** [lushen124/Universal-FE-Randomizer#19]
I run the exe and I get a bried picture of yune for half a second before it just closes. I've also tried running the jar through java and it won't even open from there.

**Comment by Y-Guy** [comment]
Turns out i just needed to run it at x86... thought my PC was 64 bit but i guess not. sorry.

**Comment by lushen124** [comment]
The issue isn't actually because of your OS or your hardware, but your version of JRE. It turns out it's possible to install an x86 version of Java on a 64-bit version of Windows, so that's probably why.
