### ISSUE TITLE
Yune not opening on Windows x32

### ISSUE THREAD

**Issue by Krisstal** [lushen124/Universal-FE-Randomizer#2]
So I've downloaded the latest version of Java available on Windows x32 and Yune is still not opening up. I know x32 is kinda extinct but my PC is quite old so yeah.

**Comment by lushen124** [comment]
Can you try the JAR file? The EXE wrapper might be locked to x64, but the JAR should technically be x32 compatible.

**Comment by lushen124** [comment]
Actually, the JAR is still being compiled with an x64 version of SWT, so it might not open. Let me take a look at it.

**Comment by lushen124** [comment]
Hey, just as a heads up, I built a x86 (32-bit) version of the application. You can find it alongside the 64-bit version, but the 32-bit version is labeled as (x86). Let me know if that works. I ran it on a 32-bit Windows 10 virtual machine and it seems to run alright.

**Comment by Krisstal** [comment]
> Hey, just as a heads up, I built a x86 (32-bit) version of the application. You can find it alongside the 64-bit version, but the 32-bit version is labeled as (x86). Let me know if that works. I ran it on a 32-bit Windows 10 virtual machine and it seems to run alright.

Yeah, it works perfectly fine now. Thanks a bunch!
