### ISSUE TITLE
Unknown error breaks game attempting to load map

### ISSUE THREAD

**Issue by flight4590** [lushen124/Universal-FE-Randomizer#206]
When even trying to load the map for the prologue (the in game cut scene starting with Mist running over to Ike) Dolphin breaks with an error simply named "Question" coming up as a blank window over the white screen of the game trying to load the scene.  Happens with both an instance where the memory card has prior save data, and when the file for the memory is wiped, so it breaks on a brand new one.  Tested just running a vanilla rom right after and the scene and gameplay work fine (at the expense of my long dead normal run but, eh).  Anything particular that could be causing this on either end? 
![Screenshot 3_7_2020 2_21_35 AM](https://user-images.githubusercontent.com/61900519/76139334-c2b1bb80-601c-11ea-8df2-b497536d1667.png)

**Comment by lushen124** [comment]
I've only tested the stable 5.0 version of Dolphin. I have heard that development builds tend to break on this, but I haven't figured out why yet. For the time being, please use the stable 5.0 version.

**Comment by flight4590** [comment]
Thanks for the pointer!  I had a mess of a time getting to even that point alone (Now including Firefox's right click box breaking and showing blanks for most functions) so it's good to know it was that simple.  Got it to work on stable 5.0.
