### ISSUE TITLE
[FE9] Staff Sage Weapon Issue?

### ISSUE THREAD

**Issue by ClyncyeRudje** [lushen124/Universal-FE-Randomizer#215]
My Shinon randomized into an Ilyana Staff Sage. This would have been fine, but he started with a Light tome despite not having Lumina, which meant that he was completely unable to attack until I cracked open the debug menu and switched it to a Fire tome for my sanity.

I'm assuming that Yune is not currently checking for the presence of the Lumina skill exclusive to Bishops when it assigns tomes, as Light magic and Staves run off the same weapon rank. 

Here are my randomization settings, if it helps:
-- | --
Randomize Growths | Redistribute (Variance: 30%)
Adjust HP Growths | NO
Adjust STR/MAG Split | YES
Randomize Bases | Redistribute (Variance: 5)
Adjust STR/MAG Split | NO
Randomize CON | NO
Randomize Affinity | YES
Randomize Skills | Randomize Existing Skills
Adept chance | NORMAL (4.62%)
Blossom chance | NORMAL (4.62%)
Celerity chance | NORMAL (4.62%)
Corrosion chance | LOW (3.08%)
Counter chance | NORMAL (4.62%)
Daunt chance | NORMAL (4.62%)
Gamble chance | NORMAL (4.62%)
Guard chance | NORMAL (4.62%)
Miracle chance | LOW (3.08%)
Nihil chance | NORMAL (4.62%)
Paragon chance | HIGH (6.15%)
Parity chance | NORMAL (4.62%)
Provoke chance | NORMAL (4.62%)
Renewal chance | NORMAL (4.62%)
Resolve chance | NORMAL (4.62%)
Savior chance | NORMAL (4.62%)
Serenity chance | NORMAL (4.62%)
Shade chance | NORMAL (4.62%)
Smite chance | NORMAL (4.62%)
Tempest chance | NORMAL (4.62%)
Vantage chance | NORMAL (4.62%)
Wrath chance | NORMAL (4.62%)
Randomize Playable Characters | YES
Include Lords | NO
Include Thieves | NO
Include Special | YES
Mix Races for Playable Characters | YES
Allow Cross-gender Assignments | YES
Randomize Bosses | NO
Randomize Minions | NO
Force Class Change | YES
Buff Minions | Flat Buff (+10%)
Improve Minion Weapons | NO
Give Minions Skills | NO
Buff Bosses | YES (Max Boost: 5 - Linear)
Improve Boss Weapons | YES (15%)
Give Bosses Skills | NO
Randomize Rewards | Randomize with Similar Items
Randomizer Seed Phrase | was ki ga endia van jenhah van ieeya van gyaje van parce van dsier van fane

**Comment by lushen124** [comment]
Yeah, looking over the logic now, I was just dumb. I assumed that the staff rank mirrored the light rank (which, by itself, is true), but just because you can use staves doesn't mean you can use light magic. 🙃
