### ISSUE TITLE
Can't find my FE9 Rom in the Yune randomizer 

### ISSUE THREAD

**Issue by PrinceRat66** [lushen124/Universal-FE-Randomizer#219]
Pretty much just what I said above, It's an ISO file but when I browse my files with Yune it just won't show up. I previously used this with FE7 and it worked fine so I want to know what I'm doing wrong.

**Comment by lushen124** [comment]
Weird. Yune looks for any files with the extensions .GBA (for FE6, 7, and 8), .SMC or .SFC (for FE4), and .ISO (for FE9). Can you double check the extension on your file? Also, what operating system are you using?

**Comment by PrinceRat66** [comment]
Sorry went to sleep, I'm using Windows 10 and the file type is POWERISO, I've launched it in dolphin and it works fine but it just doesn't show up in Yune

**Comment by PrinceRat66** [comment]
> Weird. Yune looks for any files with the extensions .GBA (for FE6, 7, and 8), .SMC or .SFC (for FE4), and .ISO (for FE9). Can you double check the extension on your file? Also, what operating system are you using?

Sorry went to sleep, I'm using Windows 10 and the file type is POWERISO, I've launched it in dolphin and it works fine but it just doesn't show up when I'm trying to put it into Yune

**Comment by lushen124** [comment]
Sounds like it's just an ISO file with a different extension. Yune filters out anything not in the list, mostly to make it easier to find if your folder is messy like mine. You could change the extension to ISO and it should show up, but I can add an option to display all files as well.

**Comment by PrinceRat66** [comment]
> Sounds like it's just an ISO file with a different extension. Yune filters out anything not in the list, mostly to make it easier to find if your folder is messy like mine. You could change the extension to ISO and it should show up, but I can add an option to display all files as well.

I'm really not tech savvy, forgive me if I'm taking up to much of your time but how would I go about changing the extension to ISO.
