### ISSUE TITLE
Yune Freezes when I try to randomize FE9.

### ISSUE THREAD

**Issue by bencie7** [lushen124/Universal-FE-Randomizer#227]
Don't know why but whenever I press randomize the loading bar will fill up almost 50% to randomizing classes and then freeze and won't move.

**Comment by lushen124** [comment]
There are some settings that are problematic in the initial build that will freeze up. I have a fix for these in the next release. You probably have one of the following settings set:

* Randomized Classes > Include Special Classes
* Fully Randomized Growths + Adjust HP Growths
* Buff Bosses + Ease In/Out

The upcoming release will have more detailed error messages when things go wrong.

If you're on Windows, you can give the build in https://github.com/lushen124/Universal-FE-Randomizer/issues/199 a try (second to last comment). That build fixes those particular issues, but not any other issues. I'll have an updated build out in the next couple of weeks.

**Comment by lushen124** [comment]
Closing this for the time being, with 0.9.1 officially released. If 0.9.1 continues to have issues, feel free to file another bug. :)
