### ISSUE TITLE
FE9 Archers getting unusable weapons

### ISSUE THREAD

**Issue by Mat8071** [lushen124/Universal-FE-Randomizer#229]
Enemy minions randomizing into archers are often equipped with Rolf's bow (I actually haven't seen a single one who's not equipped with that, but I've only got to chapter 10) and they can't use it, effectively making them unarmed enemies. I have never seen this happen with other classes and I don't have an archer in my team yet (not counting Rolf), so I don't know if this only happens to enemies.

**Comment by lushen124** [comment]
This should be resolved in 0.9.1, first because I made Rolf's bow only available for playable characters and secondly because I make sure playable characters with this bow have the appropriate lock to use the bow.
