### ISSUE TITLE
Summons don't work

### ISSUE THREAD

**Issue by Krisstal** [lushen124/Universal-FE-Randomizer#23]
Something I forgot to mention in the other issue, but summoning doesn't work. I promoted my Ephraim from Shaman to Summoner and the option to Summon doesn't even pop up. I also got Saleh as a prepromoted Summoner, and in his case the option does appear, but when I select it he doesn't summon anything. I've checked with FEGBABuilder and both of them are indeed set in the "able to summon" list, so I don't know what could be happening here.

**Comment by lushen124** [comment]
Hmm... I had three addresses written in my old randomizer, but the new one only writes one. I wonder if there's separate tables to see who can summon and what they actually summon. Let me go back to the old randomizer logic and see if that works. I'm pretty sure it was working in the old one...

In any case, thanks for the report! 👍

**Comment by lushen124** [comment]
Actually, you can probably confirm the issue for me. If you have a hex editor, you can go to the three pointers that should exist. They probably don't all match in your randomized version, but you can check it. The three offsets are:

* 0x2442C
* 0x7AD54
* 0x7AE00

By default, if there's not enough summoners, Yune doesn't repoint this table, but if there's more than the usual three, then Yune does, but it only writes that address to the first of those offsets above. The default values at those offsets are A4 F5 95 08, but if it needed to repoint, that first one probably has something like XX XX XX 09, while the other two remain unchanged. You could fix it by copying and pasting the 4 bytes from the first offset to the other two offsets. I think that should fix it. I'll put in a fix for Yune too.

**Comment by lushen124** [comment]
I'm going to close this bug since I believe it to be fixed in 0.8.0. If there are other issues with summons, please open a new ticket.
