### ISSUE TITLE
FE9: Regular enemies stopped being randomized after Chapter 12. 

### ISSUE THREAD

**Issue by Etterbeer** [lushen124/Universal-FE-Randomizer#234]
Title says it all. Enemies were just as in the vanilla game after chapter 12 (So started during the Gatrie/Astrid chapter). Pretty sure inventory also was no longer randomized.

**Comment by lushen124** [comment]
Ah, I see. Apparently between Chapters 13 and 17, the game uses PIDs of a different format for minions. I'll put in a fix for the next version. Thanks for the report!
