### ISSUE TITLE
FE9: Crash after second move from Seeker on chapter 12

### ISSUE THREAD

**Issue by Etterbeer** [lushen124/Universal-FE-Randomizer#235]
Game crashed after the second time Seeker moved. During this turn, checking his inventory also crashed the game. Before that point, only issue is that he showed up as a shadow Ike.

**Comment by lushen124** [comment]
Do you have a changelog for what class Seeker changed into?

**Comment by Etterbeer** [comment]
![image](https://user-images.githubusercontent.com/25210771/78593151-74275500-7846-11ea-9610-e3da17415f1f.png)
![image](https://user-images.githubusercontent.com/25210771/78593230-9325e700-7846-11ea-9267-3c1f237316fd.png)



Perhaps worth noting: He was carrying two brave axes that he could not use on the initial run that crashed. He had two steel lances after resetting and I rushed him before he could move.. 

Also, his HP value read something like 40/36 (Current HP/Max HP). This was also the case with other Shadow Ikes.

**Comment by lushen124** [comment]
The bug with the diff application probably caused a lot of seemingly unrelated issues, this included. We can re-open another bug if it happens again.
