### ISSUE TITLE
FE9: Thief Ike doesn't have knives in Chapter 1

### ISSUE THREAD

**Issue by Mat8071** [lushen124/Universal-FE-Randomizer#236]
My Ike randomized into a thief. He had a knife in the prologue, but then he started Chapter 1 with 4 iron swords and no knife.
![GFEE01-2](https://user-images.githubusercontent.com/61936958/78580566-dc6c3b80-7832-11ea-9a7e-1bdd5b0dd6b2.png)
![GFEE01-1](https://user-images.githubusercontent.com/61936958/78580560-daa27800-7832-11ea-8734-f4fef0e94c9c.png)

**Comment by lushen124** [comment]
Hmm... I probably forgot to account for knives as a valid weapon type. I'll put in a fix for the next version. Thanks for the report!
