### ISSUE TITLE
FE9: Randomized Bosses to bishops have no light magic tome

### ISSUE THREAD

**Issue by Etterbeer** [lushen124/Universal-FE-Randomizer#237]
I am assuming this is a bug, but could just be unlucky. Both bosses that have been randomized into a bishop so far did not spawn with usable light magic tome. Instead, they were equipped with a Torch Staff and a Warp staff respectively.

**Comment by lushen124** [comment]
This is probably a bug because bosses are required to have at least one weapon. I'll take a look.

**Comment by Etterbeer** [comment]
I have seen the same with a Valkyrie boss, that only had a Sleep staff equiped.
