### ISSUE TITLE
FE9: Ena still a dragon in chapter 21 despite being labeled a bishop

### ISSUE THREAD

**Issue by Etterbeer** [lushen124/Universal-FE-Randomizer#239]
Ena should have become a bishop, but remained a dragon laguz. One without a breath weapon even. 

![image](https://user-images.githubusercontent.com/25210771/78608626-882c8000-7861-11ea-9775-2d4841f6407b.png)

Probably a similiar issue to previous ones that I've seen on here like Rolf and Mia not becoming what they should.

**Comment by lushen124** [comment]
Yeah, going to have to look into chapter scripting to see if they're doing something weird. It's becoming increasingly clear that there is something that is overriding character data for some characters.
