### ISSUE TITLE
FE9 Randomized enemies with unusable weapons. 

### ISSUE THREAD

**Issue by TurtwigPlayz** [lushen124/Universal-FE-Randomizer#240]
I am assuming this is a bug, but could just be unlucky.
In chapter two there was an Archer with an Iron  Axe as their only weapon:
![Capture](https://user-images.githubusercontent.com/63518111/79053797-2cfde300-7bfd-11ea-9b8d-7d11ee85207c.PNG)
In Chapter three: 
![Capture1](https://user-images.githubusercontent.com/63518111/79054075-4869ed80-7bff-11ea-91ab-ebdb7e4e76d3.PNG)
Chapter four:
![Capture2](https://user-images.githubusercontent.com/63518111/79054479-5bca8800-7c02-11ea-9ce9-7464cbdfc5a3.PNG)
I'm going to stop adding the pictures of the other instances but if you would like I can add them at your request.

**Comment by lushen124** [comment]
Interesting. I never found any of these, but there were other reports of a similar thing happening. Do you have a changelog saved? It will go through and list what these characters had originally and what they had after the randomization, so you can cross reference it.

If I were to guess, it probably also has something to do with chapter scripting overriding what the usual data says. What difficulty are you playing on? I've traditionally tested Normal and a bit of Hard, and I'm not sure if it makes a difference, but we might as well narrow things down as much as we can.

**Comment by TurtwigPlayz** [comment]
I'm playing on normal mode. In all three cases, they have the same weapon they had before randomization. I did check and this glitch seemed to be present on all three difficulties (A least for the first instance, the one in chapter 2). This probably isn't relevant but just to give you all the information I did let Oscar die in chapter 1 which is something I'm sure most players don't do.

**Comment by lushen124** [comment]
I would be surprised if Oscar dying meant a change in enemies later on, but then, I haven't gotten around to deciphering chapter scripting yet, so maybe that'll shed some light on things. If I were to guess, there are certain changes to minion classes that cause issues with the randomizer around not being able to figure out what weapons a unit can use. Alternatively, it's possible that I somehow ended up with no possible weapon candidates for a unit, which would be even weirder.

Did you enable the option to improve minion weapons, by any chance? It should be separate from minion class randomization, so it shouldn't have any issues, but that's the only other thing that could change minion inventory.

**Comment by TurtwigPlayz** [comment]
Improve minion weapons was turned off.

**Comment by TurtwigPlayz** [comment]
I have randomized again and have added a improve minion weapons as well. The same enemy as in the first picture randomized into a sword cav with an iron axe again.
![Capture3](https://user-images.githubusercontent.com/63518111/79082517-cacbdd80-7ce3-11ea-9ca6-44038e4fc278.PNG)
 Oscar died again in chapter one (still probably not relevant but an odd coincidence)
