### ISSUE TITLE
FE9 Ch18 Battle Prep Skipped

### ISSUE THREAD

**Issue by SuperPopple** [lushen124/Universal-FE-Randomizer#244]
Playing FE9 randomized and in Chapter 18, I leave base, view the pre chapter cutscene, and go right to turn one, no chance to choose my units, etc. I'm using version 9.0.0, so that may have been fixed in 9.1.0. Playing on Dolphin version 5.0-11824.

**Comment by pastherolink** [comment]
i am also having this problem but to get around it i got around it by loading a normal POR iso and starting the battle prep then saving and loading the battle prep save but then the new units dont get randomized.

**Comment by lushen124** [comment]
Yeah, I've gotten reports about this. I suspect, since this chapter has some chests, that randomized chests is probably enabled, and that's inadvertently messing with the chapter script. If it's not enabled, then I'm doubly confused, because the chapter script doesn't change otherwise.

**Comment by SuperPopple** [comment]
Random rewards is enabled.

**Comment by lushen124** [comment]
The updated logic for randomized rewards that updates at the instruction level should resolve this issue.
