### ISSUE TITLE
Issue with checksum for FE9

### ISSUE THREAD

**Issue by luigi0301** [lushen124/Universal-FE-Randomizer#263]
I’m not really sure how github works and I hope it’s ok for me to submit this here. Anyway, I downloaded Yune and it worked for one game but it doesn’t seem to let FE9 pass the checksum. I have a .wbfs file which wasn’t even showing up so I converted it to .iso which became browse-able by Yune but it said it’s not supported. Is this because my game is a .wbfs file? Is there anyway to fix this without having to download a new game? I’ve been playing FE9 and it seems to run really nicely as is. Would it be possible to add .wbfs to the checksum? Idk how this stuff actually works so I thought I’d ask. Thank you very much in advance

**Comment by lushen124** [comment]
I'm not entirely sure what a WBFS file is, but after a quick google search, these are of a different file system? They seem like they're for Wii applications, not Gamecube ISOs. I'm not entirely sure how you got FE9 in that format, but I don't have enough documentation to be able to parse those kinds of files.

Can you check if Dolphin loads your converted ISO file? If it's in the Gamecube ISO format, I might be able to read it, but the incorrect checksum means it doesn't match what a direct rip of the Gamecube disc has. Just to make sure, what region of the game are you trying to use? I currently only support the North American release of FE9.

**Comment by luigi0301** [comment]
I have a NA version. And yeah I’m not entirely sure how it’s a wbfs. I believe dolphin does in fact run the converted ISO but Yune says it’s not supported

**Comment by luigi0301** [comment]
Apparently it doesn’t want to use my FE4 or 6 games either. Both of which are patched with English translations. Weird. I wish I better understood how this works lol

**Comment by lushen124** [comment]
FE4 and FE6 are ideally randomized with the original Japanese ROM, as it applies the translation patch for you. Failing that, it will also accept the patched ROMs as long as they are patched with the same translation patch that Yune uses. For FE4, that would be the Project Naga translation patch (found here: https://forums.serenesforest.net/index.php?/topic/63676-fe4-translation-patch-open-beta-v7/) and for FE6, that would be the Localization patch (found here: https://forums.serenesforest.net/index.php?/topic/41095-fe6-localization-patch-v10-seriously-we-did-something/)

**Comment by luigi0301** [comment]
Interesting. I have naga patched but it didn’t read it. I might try redownloading a new clean rom and let Yune add the patch itself. Thanks. I’m sorry for the trouble...I’m really not good at this kind of stuff, but once I get it it’s amazing.

**Comment by luigi0301** [comment]
Oh and just out of curiosity...is there like a discord server for all this. It would be a lot easier for communication. Otherwise, thank you for the help. FE8 so far is the only one working for me. I then tried to get the self randomizer cuz I think the self randomizer version I had was outdated but of course when I got the new patch and even a new clean rom, it wouldn’t work... my last question is actually, does Yune have a reverse recruitment option? I see that for 8 it has a random recruitment option

**Comment by lushen124** [comment]
> Discord

I don't think there's enough people to justify managing a Discord server just for this randomizer. So far I think a lot of people just ask around in the existing communities (Serenes Forest, or the subreddit and its corresponding Discord server). Maybe once Yune starts supporting some more of the popular games, than it might be worth opening one up. But for now, I think it makes more sense to piggyback off of existing communities for how small the userbase for this is.

> Recruitment Options

Yune supports two variants of recruitment: Reverse and Random. Reverse tries to recreate the specially tuned Reverse Recruitment patches that are floating out there, though there are some things I can't tweak nearly as well within the confines of a randomizer (I may just find a finely tuned patch and use that instead for the reverse option in the future). The random option is that, but not strictly in the reverse order. There's a lot of other options that have been requested for that which were implemented, but the default settings is probably closest to what the reverse recruitment patch does when it translates units, again lacking any kind of fine tuning. What this practically means is that they probably don't play nearly as nicely as a carefully tweaked hack, but they should be mostly doable.
