### ISSUE TITLE
FE4: Request - option to allow vanilla class

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#27]
I would like it if there was an option for units to be randomized into their vanilla class, since you mentioned that units who don't have any class restriction can't get their vanilla class.

As an aside, in some 57 seeds every single one had Erinys as a Dracoknight - not one with Pegasus Knight. In my latest seed, with strict matching for child characters, I have Dracoknight Erinys but Pegasus Knight Fee, so it makes me wonder...

**Comment by lushen124** [comment]
I'm about to just make this the default. I forgot the gender thing basically makes fliers locked to the opposite option (Pegasus Knight <-> Wyvern Knight).
