### ISSUE TITLE
GTK changelog issue

### ISSUE THREAD

**Issue by LisandraBrave** [lushen124/Universal-FE-Randomizer#276]
For some reason, running the GTK version doesn't produce a usable changelog, with all the tables on the same row. This works for the first few entries, before the text wraps and it all starts overlapping
![image](https://user-images.githubusercontent.com/8226662/93005129-aafb4880-f513-11ea-8a40-8f9d9718fa30.png)

![image](https://user-images.githubusercontent.com/8226662/93005154-fdd50000-f513-11ea-82b5-77e4e32b1671.png)

This is because output is `LF` terminated, instead of `CRLF` terminated. Running the output through `sed -e 's/$/\r/'` fixes the problem, but ideally it should be done in program.

**Comment by lushen124** [comment]
Interesting. This is good to know. Part of the problem is probably that the HTML that I'm generating is relying on the platform in some cases when it should be better formatted with more proper CSS (or at least using html line breaks).
