### ISSUE TITLE
FE8: Ephraim ch10 freezes enemy turn 1 due to randomized Selena (fleet)

### ISSUE THREAD

**Issue by kevinBE** [lushen124/Universal-FE-Randomizer#278]
At the start of the enemy's first turn in Ephraim ch10 (the one where you rescue Duessel) there is a cutscene with Selena and Valter in which Selena normally leaves midway as a Fleet class.
The randomizer changed this into her randomized combat class (Entombed in my case, but it likely happens for any class unable to move over water) and then the game just freezes.

Unit 22 | Old
-------- | ---
Character ID | Selena [0x44]
Class | Fleet [0x50]
Loading Coordinates | (0, 0)
Starting Coordinates | (20, 11)
Item 1 |  
Item 2 |  
Item 3 |  
Item 4 |  

Unit 22 | New
-------- | ---
Character ID | Selena [0x44]
Class | Entombed [0x53]
Loading Coordinates | (0, 0)
Starting Coordinates | (20, 11)
Item 1 | Rotten Claw
Item 2 |  
Item 3 |  
Item 4 |

**Comment by lushen124** [comment]
Thanks for the heads up. I can probably update the logic for her specifically so that this instance of hers does not change. I was wondering when the Fleet class was ever being used, and apparently this was it.
