### ISSUE TITLE
FE6 (minor issue): Chapter 13 Zephiel vs. Cecilia Scripted Fight Glitch

### ISSUE THREAD

**Issue by Felixr22** [lushen124/Universal-FE-Randomizer#283]
Hey! First of all, awesome randomizer, loving every part of it, this is the first significant issue I've run into. Note that it is not a softlock or otherwise gamebreaking glitch, but it is still significant enough that I feel it's worth mentioning. I also don't know if this has been reported already, but I can't find any mention of it here, so I went ahead and posted this.

I used Yune 0.9.2.0 on an unedited JP version of FE6 (Yune recognized the ROM). I applied the English translation patch through Yune, and (to keep it to the relevant settings) randomized classes for playable characters and bosses (forced class change), and set weapon assignment to match rank.

Cecilia randomized into a bishop, with a Physic staff in her top inventory slot (Mend staff in slot 2, Lightning tome in slot 3). Zephiel still was a king with Eckesachs as his only weapon, I'm assuming this is intentional.

When the scripted fight between Cecilia and Zephiel initiated, a weird glitch happened. The combat started out with Cecilia using her Physic staff on Zephiel. The combat UI also was as it should be if Cecilia was healing Zephiel. Then, Zephiel's dodge animation played, followed by him getting healed anyway, despite already being at max HP. This caused his HP value to glitch out (at first it went up, until it reached 100, then it went to -9 and back up before having the last digit remain a number while the second to last digit essentially turned into white noise. Since I wasn't noticing any repeating patterns, I decided to use the fastforward function that the emulator I'm using has. After waiting... I guess about half a minute, that loop ended, Zephiel attacked, the first attack missed, the second hit but left Cecilia alive at 10 HP. Then it continued with the usual script as if Cecilia had been defeated, and now on turn 2 player phase, Zephiel is standing at the castle with 70/70 HP.

I'd suggest having the randomizer force Cecilia to have a weapon in her top inventory slot, as I'm pretty sure the issue must've been caused by the scripted event forcing her into combat while holding a staff.

I understand if this has relatively low priority as it's a minor issue that only occurs in somewhat specific circumstances, but I thought I'd give you a heads up about this anyway. Thanks for the amazing work so far, and it's great to see you're still working on making it even better!

**Comment by lushen124** [comment]
It's definitely something worth fixing. I had another report of this as well, but it's good to have this here. You are correct in the cause of it (or at least it matches the theory I have). It shouldn't be too hard to make sure her attacking weapon is the top slot.
