### ISSUE TITLE
[FE8] Are monster classes special classes?

### ISSUE THREAD

**Issue by blackarchon** [lushen124/Universal-FE-Randomizer#286]
I'm using these randomization settings for The Sacred Stones:
![Yune_0 9 2_FE8](https://user-images.githubusercontent.com/2006570/94350784-0ec45c00-0052-11eb-9d93-71db6b8de817.png)

I specifically unchecked "Include Special Classes" in the section "Randomize Playable Characters" to avoid getting monster classes for my units. But if I look at the change
[changelog.txt](https://github.com/lushen124/Universal-FE-Randomizer/files/5287376/changelog.txt)
log, I see that Dozla is a Gorgon, Cormag is a Gargoyle and Eirika is a Revenant.

So do I misinterpret the setting "Include Special Classes" or is this a bug?

**Comment by lushen124** [comment]
Hmm... Maybe I should rephrase that option. Special classes I usually use to mean classes like Dancers or any other unique classes that only belong to one or a couple characters. The option you're looking for is to uncheck "Mix Monster Classes" which allows monster classes to be assigned to humans and vice versa. I don't have an option to only enable that only for minions or bosses if that's what you're looking for, though I could look into adding it in.

**Comment by blackarchon** [comment]
I'm dumb... you are right, there already is such an option. Sorry to bother you... :)
