### ISSUE TITLE
FE9 Tweaks

### ISSUE THREAD

**Issue by lushen124** [lushen124/Universal-FE-Randomizer#288]
* Add Vigilance and Insight to the skill randomization pool.
* Increase the chance of random rewards generating Master Seals.
* Give Assassins the ability to open chests by default.
* Dial down the adjustment for Laguz units becoming Beorc units from 1.5x transform bonuses to 0.5x transform bonuses.

**Comment by blackarchon** [comment]
Are you watching Mangs' current playthrough of randomized FE9 on Youtube? These changes sound like you do. :)

**Comment by lushen124** [comment]
Of course. Being able to routinely test so late into the game is impractical, to say the least (considering I can't load a save with a different ISO without causing issues). I usually rely on the changelog to tell me if things are bugged, but that won't ever be as good as seeing somebody get to late game. For all of my theory, I'm never sure whether the game handles something properly or not, or if there are other side effects for a change,  Playthroughs in general have been a great source of bugs and improvements that I can make.  🙂

**Comment by blackarchon** [comment]
I'm eagerly awaiting your 0.9.3 release! His randomized playthrough started my desire for playing FE9 again. :)
