### ISSUE TITLE
Add option to prevent enemy buffs from raising defences

### ISSUE THREAD

**Issue by Vennobennu** [lushen124/Universal-FE-Randomizer#295]
I like using the Minion buff feature for added difficulty, but enemies gaining Defence, Resistance and Luck can make fighting them very time-consuming, especially on Flat buffs. It'd be nice to exclude certain enemy stats from being affected by the buff amount, or at least those three.

**Comment by lushen124** [comment]
We can certainly make that an option. Do you think it should just be DEF, RES, and LCK that shouldn't be increased?

**Comment by Vennobennu** [comment]
I think so, yeah. Enemy HP does make them more durable, but only incrementally - it doesn't make them harder to hit or render low-strength units helpless.

Possibly every stat could get a toggle for whether it could be buffed, but that might get a little crowded.
