### ISSUE TITLE
[FE4] Units with a growth over 100% aren't guaranteed to level that stat every time

### ISSUE THREAD

**Issue by BabyJames6103** [lushen124/Universal-FE-Randomizer#301]
Many of my holy blood units have growths over 100%. At first, they level up in those stats just fine, sometimes even getting two stats, but then after a couple of levels they seem to never level up that again even though they have over 100% growth in that area. I'm not entirly sure what causes it to happen and i dont know why it only happens after a couple of levels.

(This has nothing to do with the blank level up arena bug where the game forces a blank level up in long arena fights.)

**Comment by lushen124** [comment]
That's interesting. If they're getting +2s, then that growth has to be over 100%. I'm not sure what would cause it to stop all of a sudden unless they reached a cap. I'm not sure how FE4 displays the bars, but unpromoted units might have lower caps than the bar displays. What are the actual values those stats are parking at and for what class?

**Comment by lushen124** [comment]
Closing this until we have more details.
