### ISSUE TITLE
FE4: Recruitable enemies can start with Berserk-inflicting weapons

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#31]
I ran into an Ayra who started with a Berserk sword. I imagine one could run into something like, Hannibal with a Berserk *staff*, which would be much more problematic, since Berserk doesn't work at all when inflicted on player units. Probably best to not allow enemies who can be recruited to have Berserk-inflicting weapons.

**Comment by lushen124** [comment]
Makes sense. I guess I could file the recruitable enemies into a special bucket that render them ineligible to obtain player-only weapons.

**Comment by lushen124** [comment]
Can you take a look at that pull request and see if that list of units is everybody that need to be restricted? I think it is, but I don't remember if there's anybody else.

**Comment by Hozu** [comment]
That looks correct to me.
