### ISSUE TITLE
[FE9] Adjust STR/MAG by class not working

### ISSUE THREAD

**Issue by RagingFlames** [lushen124/Universal-FE-Randomizer#312]
I made a randomized FE9 iso. I was confused why all my level ups were trash so I looked at the log. I noticed that among Soren's terrible growth's he also has higher STR growths than MAG even though he is still a mage.  GitHub doesn't seem to support uploading html files, so here is the log in a zip.
[changelog.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/5488394/changelog.zip)

**Comment by RagingFlames** [comment]
It happened again in this randomized iso, this time to Volke.

[broken.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/5488870/broken.zip)

**Comment by lushen124** [comment]
Interesting. I'll look into it. It wouldn't surprise me if I missed a case in adjusting growths.

**Comment by djhatch90210** [comment]
yep, issue seems to be in FE9ClassRandomizer, when checking the classes physical/magical bias and then swapping strength/magic growth, it first updates strength and then uses that updated strength score when calculating magic. this would mean a physical character swapping to magic would get absolutely junked growths and conversely mages that are swapped to a physical class are liable to get really good strength growths.
There doesn't appear to be any issue within the STR/MAG swapping code in FE9GrowthRandomizer.

```
				character.setSTRGrowth(Math.max(character.getSTRGrowth(), character.getMAGGrowth()));
				character.setMAGGrowth(Math.min(character.getSTRGrowth(), character.getMAGGrowth()));
```
