### ISSUE TITLE
Some changelog tables display improperly in firefox

### ISSUE THREAD

**Issue by RagingFlames** [lushen124/Universal-FE-Randomizer#313]
Every single changelog.html that has been generated by Yune has messed up tables somewhere. I've uploaded a picture and a change log as an example. They display fine in chrome, but not firefox.

![tables](https://user-images.githubusercontent.com/28068199/98133062-21208980-1e8b-11eb-967b-2a12246d8b7c.png)
[broken.zip](https://github.com/lushen124/Universal-FE-Randomizer/files/5488843/broken.zip)

**Comment by lushen124** [comment]
I think this is the same issue as #276. I'm going to close this issue in favor of consolidating it with that one.
