### ISSUE TITLE
[FE9] Characters don't have bands during second play through

### ISSUE THREAD

**Issue by RagingFlames** [lushen124/Universal-FE-Randomizer#314]
When you start your second game in PoR, the game is suppose to give you "bands" that increase character growths slightly. I noticed these are absent when you use the randomizer. I'm not sure if this is intentional or a bug.

**Comment by SuperPopple** [comment]
I noticed in Chapter 3, Marcia had the Wyvern Band with my only other file at the start of Endgame. No one else has had one yet though.

**Comment by lushen124** [comment]
Ah, yes. I think those are randomized away as random rewards. I can add an option to not add or remove bands from the item randomization pool.
