### ISSUE TITLE
[FE9] A Bug that crashes my game

### ISSUE THREAD

**Issue by Zanza98** [lushen124/Universal-FE-Randomizer#315]
I'm in Chapter 12 of my randomized path of radiance playthrough and every time I fight the boss, the game crashes. He is a Wyvern Rider and has an axe equipped. He also uses the black Ike model. Is there a way I can do something about it? It's my second randomized playthrough with this randomizer and although the same boss was buggy in my first run, he didn't crash the game.

**Comment by lushen124** [comment]
This is something I'm looking at. Specifically there's a few instances of characters (mainly laguz characters) forcing a shift (which is technically a promotion). Seeker (in Ch. 12) and Muarim when you fight him (Ch. 15) exhibit this issue. I think it's a scripted transformation that I should be able to adjust in the cases where they do not transform if their class is not a transforming class (or just remove it and laguz units just stay transformed).
