### ISSUE TITLE
FE9 Chapter 10 Stealth Issue

### ISSUE THREAD

**Issue by Felixr22** [lushen124/Universal-FE-Randomizer#323]
So I was playing FE9 and all was smooth sailing, ran into some graphic issues that are already well known to exist within this randomizer, but for the rest everything was going fine. Until I reached Chapter 10.

Brom had randomized into a thief, and on turn 1, he opened his own cell door. Presumably, the same would happen if Kieran or Nephenee randomized into a thief. All three of them would be within enemy range upon opening the door on turn 1, immediately breaking stealth. With particularly unfortunate circumstances, it's possible they could die before you can even reach them.

Because of this issue, I would like for there to at least be an option to prevent Brom, Kieran and Nephenee from turning into a thief, while still randomizing thieves otherwise, or just prevent them from ever becoming thieves by default. Those seem like the most reasonable options to prevent this issue from occurring

**Comment by lushen124** [comment]
Heh, that's a new one. I didn't think about that possibility. I can definitely add that logic in. It shouldn't be too hard. The alternative is looking to try and change their Neutral AI, but that might cause other issues.
