### ISSUE TITLE
FE8 Some characters have lower base stats through randomized recruitment.

### ISSUE THREAD

**Issue by pandraos** [lushen124/Universal-FE-Randomizer#325]
While messing with FE8 randomized recruitment, I noticed that a few characters seem to have lower base stats than they do in the original game.
This is easiest to notice when the characters in question join at their actual base level.

This issue seems to be happening with Kyle, Ewan and Saleh.
Ewan and Saleh in particular join with 1 less point in every stat.

I imagine it's some edge case having to do with auto-leveling base stats.

I suspect the same might be happening in other FE games and with other characters but those are the ones that have caught my eye for now.

Thank you for this incredible tool, it's been a ton of fun to play around with!

**Comment by lushen124** [comment]
Funny thing, there's another issue that was filed that probably has to do with this. #327 lists some level discrepancies between the character data and the chapter data, and the three characters you listed just so happen to be on that list.

**Comment by lushen124** [comment]
I'm going to assume that #338 fixes this, since it addresses #327. If the root cause is not because of the level discrepancy between the two, we can open another issue and look into it further.
