### ISSUE TITLE
Request to make the choice of correctly gendered classes optional

### ISSUE THREAD

**Issue by SdeSpencer** [lushen124/Universal-FE-Randomizer#326]
This is a bit of a silly ask, but in reference to #307 & #298 can you make the decision to have characters change versions of a single class to match their gender an optional feature instead of a general change? Sometimes its a bit fun to see the wrong one chosen.

**Comment by lushen124** [comment]
Yeah, that shouldn't be too hard. Just need to figure out what to call that option. 🙃
