### ISSUE TITLE
[FE8] Super Pupil Seth's Dark magic rank is messed up

### ISSUE THREAD

**Issue by AstraCrits** [lushen124/Universal-FE-Randomizer#328]
When randomized into a T2 Pupil, Seth has a dark magic rank of E. This is all fine and dandy until you realize that Flux, the lowest level Dark tome, is a D rank spell.
Not sure if this happens to other prepromotes who randomize into this class, but it definitely happens for Seth.

Here's the settings I'm using, in case it helps:

Game Title | Fire Emblem: The Sacred Stones
-- | --
Randomize Growths | NO
Randomize Bases | NO
Randomize Constitution | +/- 5, Min: 7
Randomize Movement Ranges | NO
Randomize Affinity | YES
Randomize Weapon Power | +/- 3, (5 ~ 23)
Randomize Weapon Accuracy | +/- 20, (70 ~ 100)
Randomize Weapon Weight | NO
Randomize Weapon Durability | +/- 20, (30 ~ 60)
Add Random Effects | YES (100%)
Random Effects Allowed | Stat Boosts Effectiveness Unbreakable Brave Reverse Triangle Extended Range Critical Magic Damage Eclipse
Safe Basic Weapons | YES
Randomize Playable Character Classes | Include Lords Include Thieves Include Special Classes Assign Evenly
Randomize Boss Classes | YES
Randomize Minions | YES
Base Stats Transfer Mode | Retain Personal Bases
Force Class Change | YES
Mix Monster and Human Classes | YES
Buff Minions | Scaling Buff (Growths x1.15)
Improve Minion Weapons | 25% of enemies
Buff Bosses | Linear - Max Gain: +5
Improve Boss Weapons | 25% of bosses
Randomize Rewards | YES
Randomize Recruitment | NO
Weapon Assignment Policy | Random
Randomizer Seed Phrase | I swear to Christ...no, I swear to fuckin' Super-Mecha-Death-Christ!

**Comment by lushen124** [comment]
Hmm... I might have overlooked this. I do remember that Dark Magic had a special exception for weapon rank because of Flux being D (probably in determining equivalent weapons), but I might have only applied that to some of the logic, and not the weapon rank logic for changing classes. I'll get a fix in for that.
