### ISSUE TITLE
Request: Assign Classes Evenly to FE4

### ISSUE THREAD

**Issue by Enaluxeme** [lushen124/Universal-FE-Randomizer#345]
I feel like this option is crucial to FE4 specifically, since you field every character every map.
In base FE4, you never have more than two characters with the same class (even the swordsmen in gen 2 are either two swordmasters and one hero or two heroes and a swordmaster).
Honestly, when I first pitched the idea to you I was thinking about FE4 more than GBA games...

**Comment by lushen124** [comment]
Makes sense. I actually implemented this with every game other than FE4 at this point, so doing it for FE4 wouldn't be difficult at all.
