### ISSUE TITLE
FE6: When Randomized into another character, "Roy" cannot seize

### ISSUE THREAD

**Issue by Starwizarc** [lushen124/Universal-FE-Randomizer#35]
Upon randomizing my game using this randomizer, Roy was replaced by Karel. Everything else about Chapter One worked smoothly, until it came to Seizing the Gate at the end of the level. Upon placing Karel onto the tile, I did not have the command to Seize, as seen below.
![bugfixin](https://user-images.githubusercontent.com/48234519/53782883-3df91100-3f74-11e9-8b68-08ce4c7f1c67.PNG)

**Comment by lushen124** [comment]
Do you know what other settings you used? Was it just random recruitment?
