### ISSUE TITLE
GBA Request: Fog Randomization

### ISSUE THREAD

**Issue by Vennobennu** [lushen124/Universal-FE-Randomizer#350]
The Thracia 776 randomizer's Fog of War options are pretty fun, and a similar option would be relatively simple to implement in the GBA games. In all three games, byte +0xC in the Chapter Data structure defines the normal fog range in that chapter, or 0 if there is to be no fog...and that's basically it.

There could be two parts to this option: A % chance for given map to have Fog added (or removed, if the map has Fog in vanilla), and two number boxes defining minimum-maximum vision range for those chapters where Fog is present. So if you put in 3 and 8, a fog map could have anywhere from 3 to 8 tiles vision, discounting Thieves and Torches.

There are some potential issues: Fog of War and the Magic Seal effect create visual glitches when used together, which in effect means Fog should never have a chance to appear on the Kishuna maps in FE7. Second, some tilesets do not have proper fog palettes and look funky in Fog of War. That's a purely aesthetic problem though.

**Comment by lushen124** [comment]
That's interesting. Seems like it could be an interesting option to have more FOW maps. If it's a single byte that determines vision range, then both of your options can be easily implemented. The potential issues you raised are good to know. We can certainly test it and see what else might break and go from there. Sounds simple enough to implement, could probably fit it into 0.9.3 for a beta test.

**Comment by Vennobennu** [comment]
Thanks! I hope my multiple request submissions aren't too much of a bother. The Chapter Data structure has a few other interesting stuff to fiddle with too, especially the palette used for the map or enemy bonus levels on Hard mode (this is only used to its full potential on FE6, which scales it from 4 to 15 bonus levels depending on the chapter...7 and 8 basically just give 5 HM bonus levels for the entire game).
