### ISSUE TITLE
How to only randomize classes

### ISSUE THREAD

**Issue by theBlackMagePunk** [lushen124/Universal-FE-Randomizer#387]
Essentially I want to play through the games in the randomizer pretty normally, except I only want classes randomized and then like, growths and maybe items. But I definitely want the characters themselves to stay the same. And I don't know how to do that.

**Comment by PurdraDan** [comment]
![image](https://user-images.githubusercontent.com/85551381/152046319-0562cf7f-d530-4bc6-9dca-24329d4e32cc.png)
as long as this is not checked the characters stay the same. so just don't check that box and you will be fine

**Comment by theBlackMagePunk** [comment]
Dope. Thank you. I figured this out as soon as I saw you commented lol
