### ISSUE TITLE
FE4: Enemies should not have Warp and Return staves; castle guards should not have 1 range staves in general

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#39]
They simply can't use them, AFAIK, so they just take up an item slot for nothing. No need to exclude them as enemy drops though.

**Comment by Hozu** [comment]
Now that I think about it, enemies guarding castles should probably also be excluded from having 1 range staves in general (Heal/Mend/Recover in addition), since guarding a castle prevents them from being adjacent to another unit.. I'll have to compile a list of enemies guarding castles soon.

**Comment by Hozu** [comment]
I think this list should be all of the bosses guarding castles.

BOLDOR, CHAGALL_CH2, CHAGALL_CH3, CLEMENT, DACCAR, DIMAGGIO, DOBARL, DONOVAN, GERRARD, JACOBAN, MACBETH, MAIOS, MUNNIR, SANDIMA, VAHA, BARAN, BRAMSEL, DAGGON, DISLER, HAROLD, JUDAH, KANATZ, KUTUZOV, KUTUZOV_TURN_12, MAIKOV, MORRIGAN, YUPHEEL, ZAGAM, ARVIS_CH10, BLOOM_CH7, BLOOM_CH8, DANANN, HILDA_CH10, ISHTORE, LOMBARD, MANFROY 

Although, I did not exclude enemies with just one item. I don't know if you have logic that prevents enemies with a single item getting only a staff or something.

**Comment by lushen124** [comment]
The funny thing is, I already had this list (though it’d be good to get confirmation) to determine which bosses were eligible to receive siege tomes) 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lushen124** [comment]
So my list is missing a few (DAGGON, DONOVAN, JULIUS_FINAL, and ZAGAM), and has one additional one that is probably wrong (HILDA_FINAL) and one that's not technically a boss (CH1_GENOA_COMMANDER). I'll take your word for it, since it's been a while since I played, but I'm pretty sure the Genoa commander is the generic that guards that castle in Ch. 1.

**Comment by lushen124** [comment]
For the record, this is my final list (by chapter):

`public static final Set<Character> CastleGuards = new HashSet<Character>(Arrays.asList(
				DIMAGGIO, GERRARD,
				CH1_GENOA_COMMANDER, MUNNIR, SANDIMA,
				BOLDOR, MACBETH, CLEMENT, CHAGALL_CH2,
				JACOBAN, CHAGALL_CH3, DOBARL,
				MAIOS, DACCAR, DONOVAN,
				LOMBARD, VAHA,
				HAROLD, DANANN,
				KUTUZOV, KUTUZOV_TURN_12, ISHTORE, BRAMSEL, BLOOM_CH7,
				BLOOM_CH8, MAIKOV,
				DISLER, JUDAH,
				MORRIGAN, HILDA_CH10, ZAGAM, ARVIS_CH10,
				YUPHEEL, DAGGON, MANFROY, JULIUS_FINAL
				));`

**Comment by Hozu** [comment]
DAGGON is in... chapter 10 Miletos castle IIRC, DONOVAN appears on Silesse castle after the citizens escape, ZAGAM is at Dozel castle in endgame IIRC. Endgame Hilda is leading the squad in front of Friege castle, with a dark bishop whose name escapes me at the moment guarding the castle itself. The guard of Genoa castle is a generic commander, yeah. Sounds like you got the correct NPC there.

And one last glance tells me I missed BARAN in the list, who is said occupant of Friege castle in endgame.

**Comment by lushen124** [comment]
I did miss him. Good catch.
