### ISSUE TITLE
FE4: Gen 1 holy blood boss issues

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#40]
Probably has something to do with the blacklisting of Sigurd's holy blood. Ran into Arvis with a Yewfelle, and Andre with no holy weapon or blood despite having the force holy weapons on bosses option set.

**Comment by lushen124** [comment]
Hmm... Did I accidentally apply the logic for enemies too? Did Sigurd by chance have Ulir blood?

**Comment by Hozu** [comment]
Huh... yeah, in the seed that Arvis had the Yewfelle, Sigurd also has the blood for it. Weird.

Same with the seed that Andre had no holy blood, but in that seed Arvis had a valid holy weapon.

**Comment by lushen124** [comment]
So, I found the issue for why Arvis still has Yewfelle, but I don't have any examples of Andorey not having holy blood or holy weapon assigned with that option. Do you have a seed that does that?
