### ISSUE TITLE
FE4: Holy weapon can be assigned to a unit who can't use

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#41]
This *probably* only happens to Silvia, and that's if you don't randomize her but you do randomize holy blood. If she ends up with major Bragi, she can get the Valkyria staff from her ch 4 event despite being a dancer that can never use it.

**Comment by lushen124** [comment]
Fair. I can change the logic to make sure when promoting minor blood to major, to only potentially give holy weapons to those that can use the weapon type matching their blood. In most cases, they should be able to, but Silvia is the main exception.
