### ISSUE TITLE
Crashes on loading ROM

### ISSUE THREAD

**Issue by DaftBrick** [lushen124/Universal-FE-Randomizer#416]
Looking through the list of issues I still haven't seen any fix for this; When loading any rom (tried roms for 7 and 8 that work fine on 8.3, and 9.1 as well as a US iso for 9 that worked on 9.1, so it is seemingly not a problem with roms) and no matter what it would crash after the verifying file message comes up. I have a 64bit JRE, and have had no issues with earlier versions, only occuring on 9.3.

![Screenshot 2023-04-17 190552](https://user-images.githubusercontent.com/131083590/232636252-5970e741-2628-4e0e-aca8-dc585714c6c7.png)
This is all that I see before it crashes to desktop

Edit: Tesing a bit further, 9.2 also works fine as well, so it does seem to be purely 9.3 that I'm struggling with. I would be fine with using an earlier version if I absolutely have to, but being able to use the newer additions would also be nice

**Comment by PurdraDan** [comment]
are you sure it isn't the same as #378 ?
or iirc a problem like this one was once solved by restarting PC, seems weird but worth a try

**Comment by DaftBrick** [comment]
I can try a restart, and did get it on the 9.3 release page here on github

**Comment by DaftBrick** [comment]
Well... I'll be. Restart seems to have worked, Thanks a bunch!

**Comment by PurdraDan** [comment]
yeah i half remember this happening to me or reading about it, don't remember which, but glad it helped
