### ISSUE TITLE
Manifest?

### ISSUE THREAD

**Issue by ChumimiJ0** [lushen124/Universal-FE-Randomizer#428]
When i tried to open file it simple didn't worked. After a couple of hours cmd gave me the message "no main manifest atribute" so what manifest should i do and how it's even works if you have a spare time

**Comment by PurdraDan** [comment]
Go here and follow that guide, if that doesn't help then post what file exactly doesn't open and as what you tried to open it
https://github.com/lushen124/Universal-FE-Randomizer/blob/0.9.3/README.md#installation

**Comment by ChumimiJ0** [comment]
It

**Comment by ChumimiJ0** [comment]
It didn't helped. I tried to open it through javaw, jarfix, 7zip and winrar and nothing helped. I reinstalled java a lot of times and nothing have changed. gson-2.8.5.jar used to open for for a hot second and immideatly slosed but now it just doesn't open at all. 
Java version of minecraft works perfectly fine so issue is probably not java

**Comment by PurdraDan** [comment]
the gson-2.8.5.jar file is not what you should be opening. You have to get a yune file of the latest version, just scroll down on the following link:
https://github.com/lushen124/Universal-FE-Randomizer/releases
until you get here:
![image](https://github.com/lushen124/Universal-FE-Randomizer/assets/85551381/9cfe036e-a04d-461b-a2c4-8d3cbfc91331)
And from those 4 you have to pick the version for your system.
To make it easier for you:

If you have Linux Use this one:
![image](https://github.com/lushen124/Universal-FE-Randomizer/assets/85551381/1f55ad65-0cc3-4211-b8d8-fb5d32cd0bf6)
If you have a Mac Use this one:
![image](https://github.com/lushen124/Universal-FE-Randomizer/assets/85551381/13a3c76e-f0c1-49e1-b993-c86a230885eb)
If you have Windows Use one of these 2 :
![image](https://github.com/lushen124/Universal-FE-Randomizer/assets/85551381/414c739d-a52f-46ae-9d75-29ccd59a1dd0)
Important note for windows: There are two versions of the JAR and binary. The one you need depends on the version of JRE you have installed and NOT the version of Windows you have installed. That is to say, you can have a 64-bit version of Windows but still be running an x86 (32-bit) version of JRE. I recommend you update your JRE to match the architecture for your Windows installation, but if you want to retain your x86 JRE, use the x86 version. Chances are, if you see a splash screen and then nothing happens, you have the wrong version. Also, if you're trying to randomize FE9, a 64-bit JRE is required, as there isn't enough memory to randomize FE9 with 32-bit JREs.

**Comment by ChumimiJ0** [comment]
Thank you!  I couldn't have done it without you
