### ISSUE TITLE
Weapons not showing added effects.

### ISSUE THREAD

**Issue by SdeSpencer** [lushen124/Universal-FE-Randomizer#45]
Only noticed in FE8 (though i haven't checked others), but more than a few times i've noticed that the randomizer-added abilities of weapons just aren't showing up (specifically noticed with the slim lance doing half health, but i believe all or most weapons were having the same problem in the game).

Specific options and seed i had when noticing this is here: https://imgur.com/a/nDhnsR5

**Comment by lushen124** [comment]
What do you mean by not showing added effects? Do you mean the text? or is it not actually doing the effect it says it's doing?

**Comment by lushen124** [comment]
I tried your seed and got your Half HP slim lance, but it works fine and it shows up fine too in the text. You're on the latest version, right?

**Comment by SdeSpencer** [comment]
yes i'm in the latest version. It wasn't showing additional effects in the description text. It was still working as a half health weapon though.

**Comment by lushen124** [comment]
Oooh, I see what you mean. For one thing I forgot to add random recruitment settings to the changelog, but for another, it's only with random recruitment that this bug occurs. I'll have it fixed. Thanks!
