### ISSUE TITLE
Separate buffing bosses from buffing enemies.

### ISSUE THREAD

**Issue by nexusanphans** [lushen124/Universal-FE-Randomizer#55]
Buffing bosses is to be made separate from buffing enemies, thus you can choose to buff enemies but not bosses and vice versa. [Link to the discussion on reddit](https://www.reddit.com/r/fireemblem/comments/awpkhc/yune_v080_is_now_available_featuring_gbafe/ei2f4f0/?context=3).

Also, buffing bosses is to be scaled over the course of the game, instead of having a fixed extra stat points for all bosses.

Also please make it possible to upgrade bosses' weapons, because why not?

edit: How to apply labels on github?

**Comment by nexusanphans** [comment]
Please tag this for GBAFE.

**Comment by nexusanphans** [comment]
@lushen124 Please tag this for GBAFE.

**Comment by lushen124** [comment]
I was planning on applying this to both GBAFE and FE4, so I'll add both. 👍
