### ISSUE TITLE
FE4: Seliph received an invalid class demotion from Sigurd

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#59]
Strict child matching, similar promotions. Sigurd was a Mage Knight, but Seliph was a Thief. Thief has only one valid promotion under the given rules (similar promotions requires same or greater bases + class skills), which is Rogue. That ends up breaking the other rule of retain mounts (I'm assuming units who promote into a mounted class from a foot class always promote into a mounted one if retain mounts is enabled - is that correct?).

**Comment by lushen124** [comment]
Strict child matching shouldn't put Seliph as a Thief... do you have the seed you used?

**Comment by Hozu** [comment]
[Here is the changelog.](https://www.dropbox.com/s/rjqrwcci6yc344v/FE4%20rando%2059.html?dl=0)

**Comment by lushen124** [comment]
Oh... Mage Knight with Major Od. I think it tries to make Seliph a sword user because of it.

Perhaps if the parent has major blood, it should match the class first instead of the blood.

As for the mounts, promotion is not included here, so no, somebody that normally gains a mount on promotion is not guaranteed to still get one on promotion. We could add that though. IIRC, the only characters that have this trait are Leif, Seliph, Lachesis, and Azelle.

**Comment by Hozu** [comment]
Might be a good idea to make sure they can promote into mounts, even though it limits more characters to horses. Mostly for Seliph, since randomizing lord + retain mount is a way to randomize the lords while ensuring they're mounted so maps don't drag on due to footlocked lords.

Now that I think about it, there's also the case where Nanna can be in an unmounted pre-promote class despite having retain mounts on due to her mother getting such a class and it being passed via strict matching. I don't know if retain mount plays a role in loose parental matching or random child class. Not sure if that's something that should be addressed though.

**Comment by lushen124** [comment]
So I found this chunk of code for Seliph specifically that states that if we're not using strict promotions, make sure Seliph can use the weapon that Sigurd passes down, which I suspect is there for another issue. I don't think there's a reason to make sure the base class can use it for this case though. As long as his promoted class can use it, that should be sufficient.

**Comment by lushen124** [comment]
As for the retain mount on promotions, that's something that needs a bit more discussion, I think. I'm just imagining all the cases where this constraint might not be possible, when combined with strict matching. Lachesis for example, is considered a unit that is land-locked. Having an option that ensures she promotes into a horseback unit is going to conflict if she ends up in a class that doesn't have a horseback option, especially if combined with strict promotions.

**Comment by Hozu** [comment]
re: the code for Seliph to ensure that he can use the weapon that Sigurd passes down, there used to be an issue where you'd get something like, Warrior Sigurd w/ the bow, and then you get Fighter -> something that can't use bows for Seliph. Or something like that. I don't think I have the changelogs from when that was an issue.

You may have to have a list of pre-promoted classes that have a mounted promoted class as a possible option via similar promotions (and probably another for fixed promotions?). And then restrict the units in question to those unpromoted classes when using the appropriate option. Thankfully you don't have to account for enemy-only promoted classes because there aren't any.

**Comment by lushen124** [comment]
Right, so in your case, there is no winning here, as no base classes will be able to use both magic and swords, so he's going to lose something. The fix I have right now will make Seliph a mage, as that's more accurate to what he's supposed to be if Sigurd is a Mage Knight. His promotion is still going to match Sigurd's so he'll be able to use the weapons eventually. I do think this is a better approach, but we might have to revisit this later. I'll make the change for 0.8.2.

As for the retain mount for promotions, let's make a separate ticket for that.
