### ISSUE TITLE
Stuck on Loading Class

### ISSUE THREAD

**Issue by Fridgered** [lushen124/Universal-FE-Randomizer#63]
I've been trying to randomize my favourite fire emblem game being FE4 but every time I try I get stuck on "Loading Class D" which I assume is Loading ClassDataLoader but its not going any further.
I have waited five hours and it's not finishing, is it just my rom or do I not have a certain file? I downloaded the excusable and the 64 bit one won't launch and the 82x one actually launches but does this.
I haven't tested if it works for the GBA fire emblem as they all result in Checksum failure. 
![Screenshot (19)](https://user-images.githubusercontent.com/30985114/54198923-08858380-449e-11e9-9e84-2c1a9925da40.png)

**Comment by lushen124** [comment]
It definitely shouldn’t take that long, and definitely not on loading class data. What version of Java JRE do you have installed? Do you know if your ROM is headered? You can tell by the size. I believe the headered ROM will be listed as 4097 bytes as opposed to 4096 in the unheadered version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fridgered** [comment]
I have 1.8 and im at 4097

**Comment by Fridgered** [comment]
Its been 15 minutes and it's still getting stuck in the same place even after I found an unheaded ROM (4096) could you please help me again I don't understand what I'm doing wrong.

**Comment by lushen124** [comment]
Headered and unheadered should both work, but if the same issue is happening on both then it sounds like a different issue. Can you take a look at what version of the JRE you have? You should be able to see it from the Java Control Panel.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fridgered** [comment]
I have java version "1.8.0_201" 
![Screenshot (20)](https://user-images.githubusercontent.com/30985114/54224901-db9e9400-44d0-11e9-9560-b6622e8f52f0.png)

**Comment by lushen124** [comment]
If you can run it, you have JRE though you have a relatively old version of Java (Java 8).

https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html

That’s Java 11, which is what I do my primary testing on. You should get a 64-bit JRE if you have a 64-bit CPU (and use the x64 executable in that case).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lushen124** [comment]
I’ll take a look at x86 when I get off work tonight if you don’t have a 64-bit PC, as there’s no x86 support for the newest JRE anymore.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fridgered** [comment]
That's odd my Java says I have the latest version but I can attempt to figure this out. You really don't have to go out of your way for me that's alright. Sorry for bothering you at work.

**Comment by Fridgered** [comment]
I set it up to run Java 11 however its been roughly 15 minutes and I'm still stuck on loading class data I really don't get it.
![Screenshot (21)](https://user-images.githubusercontent.com/30985114/54235600-f3cddd80-44e7-11e9-9f09-adb904226650.png)

**Comment by lushen124** [comment]
Ok, so I noticed one thing that shouldn't happen but is happening right now for you, and that's the fact that promotions has no options selected. I think if you select an option, it should start working, but I'll look into why it's not selected by default.

**Comment by Fridgered** [comment]
There it worked finally! Thank you so much for the assistance, I'll draw you something soon as an apology for taking so much time.
