### ISSUE TITLE
[FE 6] Randomized Yoder Inventory

### ISSUE THREAD

**Issue by jugglerpanda** [lushen124/Universal-FE-Randomizer#65]
I am playing a random recruitment version of FE6 and have just reached the chapter Yoder joins your army. He joined as a Valkyrie, but instead of joining with the legendary from the other route and the legendary staff, he joined with a Forblaze and a physic staff. As I'm missing 2 of the legendary items, I'm worried that this will lock me out of the "good" ending.

**Comment by lushen124** [comment]
Oh! Nice catch. I forgot about his inventory. I’ll have to look at that chapter specifically because, iirc, he gives you a different weapon based on which route you didn’t take, so I’ll have to see how his inventory is coded.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
