### ISSUE TITLE
FE4: Leif received Troubadour class via strict matching

### ISSUE THREAD

**Issue by Hozu** [lushen124/Universal-FE-Randomizer#71]
Ethlyn was Troubadour, so with strict child class matching that caused Leif to become one as well. Ethlyn can get only one female-locked class, so it might be better to ensure Leif gets a different class (like Cavalier) instead of locking Ethlyn out of the class. Even if that means he can't inherit staves that way.

**Comment by lushen124** [comment]
Makes sense. I might just end up assigning Leif the male version of whatever Ethlyn is in that case (which means he basically won't ever be Prince, because Ethlyn will never be a Princess.
