### ISSUE TITLE
FE4 Suggestion: Randomize class skills, and childrens's parental influence.

### ISSUE THREAD

**Issue by rosearc** [lushen124/Universal-FE-Randomizer#87]
The first is an option to set/randomize how many and which skills every class gets as class skills, with promoted classes settings set apart. Additional options: which class skills are part of the pool(s); all mounted/thief/armored classes get Canto/Steal/Pavise respectively as one of their skills, and/or limiting the previous skills to said classes pools; all class skills purely randomized or no skills are lost upon promotion (only applies to normal class promotion paths).

The second is to, for every non-Seliph set of children, randomize who inherits primarely from the mother and who from the father; maybe with an option to not randomize Leif and Altenna's inheritance.

**Comment by lushen124** [comment]
Parental influence should be ok, I think? I'm not sure if it would break anything, but I don't think it should break anything.

Class skills is doable, though I'm not sure if there's a limit of skills a character can display in the menu. It's more of an issue with child characters, which can inherit a ton of skills, and can be disjoint from class skills. I think adding 1 class skill should be ok, but more than that is a bit iffy. Additionally, the amount of space in the UI to support a feature would be difficult to fit in, especially if it needs another selection from a large number of possible skills. I want to try to avoid expanding the window more than it already is now. So as a first pass, maybe a single option to randomly assign class skills, maybe with a chance that you can specify for 0 or 1 skills.

**Comment by rosearc** [comment]
The max amount of skills able to have on a single unit in vanilla is 6 (Swordmaster Noish/Lex/Dew!Larcei), which is technically already able to be surpassed by pairing 2 parents with 3 non-Pursuit skills with a myrmidon child; I don't think it should break anything gameplay wise but it might look weird. I would still like to lock Canto to mounted units but I see what you mean about the UI window already being big enough as is, thank you nonetheless :')

**Comment by lushen124** [comment]
After thinking about it a bit more, parental influence might actually be problematic. There's some logic in place to make sure specific children get classes assigned appropriately so that they can use their parent's holy weapons, specifically Altena (which you mentioned) and the other I know of is Febail, who needs Yewfelle (not to mention Patty, who may be required to stay as a thief). Then there's those that must be healers (Lana/Coirpre), those that must be dancers (Lene), and those that need to be fliers (Fee/Altena). In fact, I think Larcei/Ulster might be the only pair that don't really care. I think there's too many combinations of settings for flipping primary influence for the kids to be feasible.

**Comment by lushen124** [comment]
As for the class skills to be randomly assigned, after looking at what I have to work with, I'm not sure this is really worth it as there is a limited set of skills that are available as class skills. They are: 

* Canto
* Great Shield
* Wrath
* Pursuit
* Adept
* Steal
* Charm
* Critical

It's a small set and I don't see anything particularly interesting in there. Nihil, Miracle, Charge, Renewal, or any of the sword skills would be interesting. Charm is kind of interesting, but the others just seem like they'd be overpowered on both your characters and the enemy minions.

**Comment by rosearc** [comment]
Mmmmh I see; I was thinking on unrestricted class changes only so fixed holy weapon inheritance flew right over my mind (the chance of passing Forsetti onto a Bard Lana does sound pretty rad tho :p), but you are right.

And ooof, that's a smaller of skills than I thought would be available. I hoped classes that are overshadowed by others (such as Heroes by Swordmasters) could find a niche with randomized class skills but that's... yeah. Especially if Wrath and Steal are in the pool that could break the game or make it way too tedious as soon as Prologue. Too bad, but no big deal; thank you and sorry for the bother.
