### ISSUE TITLE
FE8 Scaling Buff to Enemy Growth not Working

### ISSUE THREAD

**Issue by koumal8** [lushen124/Universal-FE-Randomizer#93]
It's me again, on Mac OS High Sierra in case it was relevant: buffing enemy growths in FE8 through the scaling method isn't working. I haven't tried fe7 and fe6 yet. I would attach the generated changelog for proof but github doesn't like html files it would seem :(

**Comment by lushen124** [comment]
Changelog would be helpful just to see what it actually changed for the enemies if it's not working. The OS shouldn't matter, but it's still good to know.

**Comment by koumal8** [comment]
https://www.dropbox.com/s/gxld97udhu3pkfk/FE8RR.html?dl=0

Don't know why I didn't think of dropbox before
